/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel;

import SqlMetodos.Entrada_sql;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import sub_jpanel.newEntrada_Buscar;
import sub_jpanel.newEntrada_Editar;
import sub_jpanel.newEntrada_Nueva;

/**
 *
 * @author Julio Ramirez
 */
public class Entrada_vista extends javax.swing.JPanel {
    int width=890, height=630;
    boolean seleccion= false;
    Entrada_sql metodos_entradas= new Entrada_sql();
    String codigo;
    Date f_ingreso;
    
    public Entrada_vista() {
        initComponents();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jpanel_entradaProd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlabel_buscar_producto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_ENTRADAPRODUCTOS = new javax.swing.JTable();
        jlabel_nueva_entrada = new javax.swing.JLabel();
        jlabel_editar_entrada = new javax.swing.JLabel();

        setBackground(new java.awt.Color(43, 43, 43));
        setForeground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(890, 660));
        setMinimumSize(new java.awt.Dimension(890, 660));
        setPreferredSize(new java.awt.Dimension(890, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(43, 43, 43));
        fondo.setForeground(new java.awt.Color(153, 153, 153));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel_entradaProd.setBackground(new java.awt.Color(43, 43, 43));
        jpanel_entradaProd.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRADA DE PRODUCTOS");

        jlabel_buscar_producto.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_producto.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_buscar_producto.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editar_entrada.png"))); // NOI18N
        jlabel_buscar_producto.setText("BUSCAR ENTRADAS (FECHA)");
        jlabel_buscar_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_buscar_productoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_buscar_productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_buscar_productoMouseExited(evt);
            }
        });

        TABLA_ENTRADAPRODUCTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Tipo", "Encargado", "Almacen", "Cantidad", "Fecha"
            }
        ));
        TABLA_ENTRADAPRODUCTOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLA_ENTRADAPRODUCTOSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLA_ENTRADAPRODUCTOS);

        jlabel_nueva_entrada.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_nueva_entrada.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_nueva_entrada.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_nueva_entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nueva_entrada.png"))); // NOI18N
        jlabel_nueva_entrada.setText("NUEVA ENTRADA");
        jlabel_nueva_entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_nueva_entradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_nueva_entradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_nueva_entradaMouseExited(evt);
            }
        });

        jlabel_editar_entrada.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_editar_entrada.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Editar_producto.png"))); // NOI18N
        jlabel_editar_entrada.setText("EDITAR ENTRADA DE PRODUCTO");
        jlabel_editar_entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_editar_entradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_editar_entradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_editar_entradaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpanel_entradaProdLayout = new javax.swing.GroupLayout(jpanel_entradaProd);
        jpanel_entradaProd.setLayout(jpanel_entradaProdLayout);
        jpanel_entradaProdLayout.setHorizontalGroup(
            jpanel_entradaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_entradaProdLayout.createSequentialGroup()
                .addGroup(jpanel_entradaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanel_entradaProdLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_entradaProdLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jlabel_nueva_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(345, 345, 345)
                        .addComponent(jlabel_buscar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_entradaProdLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_entradaProdLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_entradaProdLayout.createSequentialGroup()
                .addComponent(jlabel_editar_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(311, 311, 311))
        );
        jpanel_entradaProdLayout.setVerticalGroup(
            jpanel_entradaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_entradaProdLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jpanel_entradaProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_entradaProdLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jlabel_nueva_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlabel_buscar_producto))
                .addGap(29, 29, 29)
                .addComponent(jlabel_editar_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondo.add(jpanel_entradaProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 670));

        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel_buscar_productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_productoMouseEntered
        jlabel_buscar_producto.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_buscar_productoMouseEntered

    private void jlabel_buscar_productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_productoMouseExited
         jlabel_buscar_producto.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_buscar_productoMouseExited

    private void jlabel_nueva_entradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_entradaMouseClicked
        newEntrada_Nueva nueva= new newEntrada_Nueva();
        addConatiner(nueva, width, height, jpanel_entradaProd);
    }//GEN-LAST:event_jlabel_nueva_entradaMouseClicked

    private void jlabel_nueva_entradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_entradaMouseEntered
          jlabel_nueva_entrada.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_nueva_entradaMouseEntered

    private void jlabel_nueva_entradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_entradaMouseExited
        jlabel_nueva_entrada.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_nueva_entradaMouseExited

    private void jlabel_editar_entradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_entradaMouseEntered
          jlabel_editar_entrada.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_editar_entradaMouseEntered

    private void jlabel_editar_entradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_entradaMouseExited
        jlabel_editar_entrada.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_editar_entradaMouseExited

    private void jlabel_editar_entradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_entradaMouseClicked

        if(seleccion == true){
            newEntrada_Editar nueva= new newEntrada_Editar();
            addConatiner(nueva, width, height, jpanel_entradaProd);            
            /*Metodo de captura de datos*/
            nueva.captura_Datos(codigo, f_ingreso);
            
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
        
    }//GEN-LAST:event_jlabel_editar_entradaMouseClicked

    private void jlabel_buscar_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_productoMouseClicked
        newEntrada_Buscar nueva= new newEntrada_Buscar();
        addConatiner(nueva, width, height, jpanel_entradaProd);
    }//GEN-LAST:event_jlabel_buscar_productoMouseClicked

    private void TABLA_ENTRADAPRODUCTOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_ENTRADAPRODUCTOSMouseClicked
        seleccion = true;
        
        int row_select = TABLA_ENTRADAPRODUCTOS.getSelectedRow();
        codigo = TABLA_ENTRADAPRODUCTOS.getValueAt(row_select, 0).toString();
        String f_i = TABLA_ENTRADAPRODUCTOS.getValueAt(row_select , 6).toString(); //Seleccion d ela fecha en la tabla
        String conversion_f = f_i.substring(0, 10);
        System.out.println("Fecha obtenida: "+ conversion_f);
        try {
                f_ingreso =new SimpleDateFormat("yyyy-MM-dd").parse(conversion_f) ;               
        } catch (ParseException ex) {
                System.out.println("Erro al parsear:" + ex);
        } 
        
        
        System.out.println("Selecione la fila: " + row_select+"Codigo obtenido: " +codigo);
    }//GEN-LAST:event_TABLA_ENTRADAPRODUCTOSMouseClicked

    
    
    
    public void Look() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {

        } catch (IllegalAccessException ex) {

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLA_ENTRADAPRODUCTOS;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlabel_buscar_producto;
    private javax.swing.JLabel jlabel_editar_entrada;
    private javax.swing.JLabel jlabel_nueva_entrada;
    private javax.swing.JPanel jpanel_entradaProd;
    // End of variables declaration//GEN-END:variables

     public void addConatiner(JPanel p,int width, int height,JPanel c){
        p.setSize(width,height);
        p.setLocation(0,0);
        c.removeAll();
        c.add(p,BorderLayout.CENTER);
        c.revalidate();
        c.repaint();
    }
     

    public void listar(){
        TABLA_ENTRADAPRODUCTOS.setModel(metodos_entradas.listar_entrada());
    } 
     
}
