/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import sub_jpanel.Historial_Buscar;
import sub_jpanel.Historial_Propiedades;


/**
 *
 * @author Julio Ramirez
 */
public class Historial_vista extends javax.swing.JPanel {
     int width=890, height=630;
    /**
     * Creates new form Inicio
     */
    public Historial_vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel_fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlabel_propiedadesHistorial = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlabel_buscar_producto = new javax.swing.JLabel();
        jlabel_editar_entrada = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(890, 660));
        setMinimumSize(new java.awt.Dimension(890, 660));
        setPreferredSize(new java.awt.Dimension(890, 660));

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_fondo.setBackground(new java.awt.Color(43, 43, 43));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORIAL");

        jlabel_propiedadesHistorial.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_propiedadesHistorial.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_propiedadesHistorial.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_propiedadesHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Editar_producto.png"))); // NOI18N
        jlabel_propiedadesHistorial.setText("PROPIEDADES");
        jlabel_propiedadesHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_propiedadesHistorialMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_propiedadesHistorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_propiedadesHistorialMouseExited(evt);
            }
        });

        jlabel_buscar_producto.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_producto.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_buscar_producto.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buscar_inventario.png"))); // NOI18N
        jlabel_buscar_producto.setText("BUSCAR PRODUCTO ");
        jlabel_buscar_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_buscar_productoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_buscar_productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_buscar_productoMouseExited(evt);
            }
        });

        jlabel_editar_entrada.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_editar_entrada.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/EXCEL.png"))); // NOI18N
        jlabel_editar_entrada.setText("TRASPASAR DATOS");
        jlabel_editar_entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_editar_entradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_editar_entradaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_fondoLayout = new javax.swing.GroupLayout(jPanel_fondo);
        jPanel_fondo.setLayout(jPanel_fondoLayout);
        jPanel_fondoLayout.setHorizontalGroup(
            jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jlabel_editar_entrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabel_buscar_producto)
                .addGap(107, 107, 107))
            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_fondoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_fondoLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jlabel_propiedadesHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel_fondoLayout.setVerticalGroup(
            jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fondoLayout.createSequentialGroup()
                .addGroup(jPanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_fondoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlabel_buscar_producto)
                        .addGap(4, 4, 4))
                    .addComponent(jlabel_editar_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlabel_propiedadesHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(412, 412, 412))
        );

        fondo.add(jPanel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel_editar_entradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_entradaMouseEntered
       jlabel_editar_entrada.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_editar_entradaMouseEntered

    private void jlabel_editar_entradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_entradaMouseExited
        jlabel_editar_entrada.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_editar_entradaMouseExited

    private void jlabel_buscar_productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_productoMouseEntered
        jlabel_buscar_producto.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_buscar_productoMouseEntered

    private void jlabel_buscar_productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_productoMouseExited
         jlabel_buscar_producto.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_buscar_productoMouseExited

    private void jlabel_propiedadesHistorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_propiedadesHistorialMouseExited
        jlabel_propiedadesHistorial.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_propiedadesHistorialMouseExited

    private void jlabel_propiedadesHistorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_propiedadesHistorialMouseEntered
         jlabel_propiedadesHistorial.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_propiedadesHistorialMouseEntered

    private void jlabel_propiedadesHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_propiedadesHistorialMouseClicked
        Historial_Propiedades nuevo = new Historial_Propiedades();
        addConatiner(nuevo, width, height, jPanel_fondo);
    }//GEN-LAST:event_jlabel_propiedadesHistorialMouseClicked

    private void jlabel_buscar_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_productoMouseClicked
        Historial_Buscar nueva= new Historial_Buscar();
        addConatiner(nueva, width, height, jPanel_fondo);
    }//GEN-LAST:event_jlabel_buscar_productoMouseClicked

    public void Look() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {

        } catch (IllegalAccessException ex) {

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel_fondo;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlabel_buscar_producto;
    private javax.swing.JLabel jlabel_editar_entrada;
    private javax.swing.JLabel jlabel_propiedadesHistorial;
    // End of variables declaration//GEN-END:variables
    public void addConatiner(JPanel p,int width, int height,JPanel c){
        p.setSize(width,height);
        p.setLocation(0,0);
        c.removeAll();
        c.add(p,BorderLayout.CENTER);
        c.revalidate();
        c.repaint();
    }
}
