/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpanel;

import BOL.Productos;
import SqlMetodos.Producto_sql;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Julio Ramirez
 */
public class Producto extends javax.swing.JPanel {

    Producto_sql metodos_prod = new Producto_sql();
    String codigo;
    int row_select;
    
    public Producto() {
        initComponents();
        listar();
        txt_Stock.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlabel_eliminar_producto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_PRODUCTOS = new javax.swing.JTable();
        jlabel_editar_entrada1 = new javax.swing.JLabel();
        jlabel_editar_entrada2 = new javax.swing.JLabel();
        jlabel_editar_entrada3 = new javax.swing.JLabel();
        jlabel_editar_entrada4 = new javax.swing.JLabel();
        txt_limite = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jcombo_Nalmacen = new javax.swing.JComboBox<>();
        jcombo_tipo = new javax.swing.JComboBox<>();
        txt_nombre = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jlabel_agregar_producto = new javax.swing.JLabel();
        jlabel_editar_producto = new javax.swing.JLabel();
        jlabel_editar_entrada5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txt_Stock = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(890, 660));
        setMinimumSize(new java.awt.Dimension(890, 660));
        setPreferredSize(new java.awt.Dimension(890, 660));

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(43, 43, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRODUCTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 10, 249, 20));

        jlabel_eliminar_producto.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_eliminar_producto.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_eliminar_producto.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_eliminar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete_prod.png"))); // NOI18N
        jlabel_eliminar_producto.setText("ELIMINAR PRODUCTO");
        jlabel_eliminar_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_eliminar_productoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_eliminar_productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_eliminar_productoMouseExited(evt);
            }
        });
        jPanel1.add(jlabel_eliminar_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 182, 160, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 870, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 870, 20));

        TABLA_PRODUCTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Tipo", "Almacen", "Cantidad", "Limite"
            }
        ));
        TABLA_PRODUCTOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLA_PRODUCTOSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLA_PRODUCTOS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 840, 332));

        jlabel_editar_entrada1.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada1.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_editar_entrada1.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada1.setText("Stock");
        jPanel1.add(jlabel_editar_entrada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, -1, 20));

        jlabel_editar_entrada2.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada2.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_editar_entrada2.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada2.setText("Nombre");
        jPanel1.add(jlabel_editar_entrada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 44));

        jlabel_editar_entrada3.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada3.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_editar_entrada3.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada3.setText("Tipo");
        jPanel1.add(jlabel_editar_entrada3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 30, 44));

        jlabel_editar_entrada4.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada4.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_editar_entrada4.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada4.setText("Almacen");
        jPanel1.add(jlabel_editar_entrada4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 70, 44));

        txt_limite.setBackground(new java.awt.Color(43, 43, 43));
        txt_limite.setForeground(new java.awt.Color(204, 204, 204));
        txt_limite.setBorder(null);
        jPanel1.add(txt_limite, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 90, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 70, 20));

        jcombo_Nalmacen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1", "2" }));
        jPanel1.add(jcombo_Nalmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 120, -1));

        jcombo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Consumible", "Unitario" }));
        jPanel1.add(jcombo_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 120, -1));

        txt_nombre.setBackground(new java.awt.Color(43, 43, 43));
        txt_nombre.setForeground(new java.awt.Color(204, 204, 204));
        txt_nombre.setBorder(null);
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 10));

        jlabel_agregar_producto.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_agregar_producto.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_agregar_producto.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_agregar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nueva_entrada.png"))); // NOI18N
        jlabel_agregar_producto.setText("AGREGAR PRODUCTO");
        jlabel_agregar_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_agregar_productoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_agregar_productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_agregar_productoMouseExited(evt);
            }
        });
        jPanel1.add(jlabel_agregar_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, 34));

        jlabel_editar_producto.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_editar_producto.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_editar_producto.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_editar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Editar_producto.png"))); // NOI18N
        jlabel_editar_producto.setText("ACTUALIZAR PRODUCTO");
        jlabel_editar_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_editar_productoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_editar_productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_editar_productoMouseExited(evt);
            }
        });
        jPanel1.add(jlabel_editar_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 178, 50));

        jlabel_editar_entrada5.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada5.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_editar_entrada5.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada5.setText("Cantidad Limite");
        jPanel1.add(jlabel_editar_entrada5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 90, 20));

        txt_Stock.setBackground(new java.awt.Color(43, 43, 43));
        txt_Stock.setForeground(new java.awt.Color(153, 153, 153));
        txt_Stock.setBorder(null);
        jPanel1.add(txt_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 80, 70, 30));

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel_agregar_productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregar_productoMouseEntered
        jlabel_agregar_producto.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_agregar_productoMouseEntered

    private void jlabel_agregar_productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregar_productoMouseExited
         jlabel_agregar_producto.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_agregar_productoMouseExited

    private void jlabel_editar_productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_productoMouseEntered
        jlabel_editar_producto.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_editar_productoMouseEntered

    private void jlabel_editar_productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_productoMouseExited
        jlabel_editar_producto.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_editar_productoMouseExited

    private void jlabel_eliminar_productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_eliminar_productoMouseEntered
        jlabel_eliminar_producto.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_eliminar_productoMouseEntered

    private void jlabel_eliminar_productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_eliminar_productoMouseExited
         jlabel_eliminar_producto.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_eliminar_productoMouseExited

    private void jlabel_agregar_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregar_productoMouseClicked
        if(!txt_nombre.getText().equals("") & !txt_limite.getText().equals("") & !jcombo_Nalmacen.getSelectedItem().equals("Seleccionar") 
                & !jcombo_tipo.getSelectedItem().equals("Seleccionar")){
            Productos p = new Productos();
            p.setNombreProducto(txt_nombre.getText());
            p.setAlmacen(Integer.parseInt(jcombo_Nalmacen.getSelectedItem().toString()));
            p.setTipo(jcombo_tipo.getSelectedItem().toString());
            p.setCantidad(0);
            p.setLimite(Integer.parseInt(txt_limite.getText().toString()));
            metodos_prod.add_Prod(p);
            vaciar();
            listar();
        }else{
            JOptionPane.showMessageDialog(null, "Termine de llenar los campos", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jlabel_agregar_productoMouseClicked

    private void jlabel_editar_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_productoMouseClicked
        if(!txt_nombre.getText().equals("") & !txt_limite.getText().equals("") & !jcombo_Nalmacen.getSelectedItem().equals("Seleccionar") 
           & !jcombo_tipo.getSelectedItem().equals("Seleccionar")){
            Productos p = new Productos();
            p.setCodigoProducto(codigo);
            p.setNombreProducto(txt_nombre.getText());
            p.setAlmacen(Integer.parseInt(jcombo_Nalmacen.getSelectedItem().toString()));
            p.setTipo(jcombo_tipo.getSelectedItem().toString());
            p.setCantidad(Integer.parseInt(txt_Stock.getText().toString()));
            p.setLimite(Integer.parseInt(txt_limite.getText().toString()));
            metodos_prod.update_Prod(p);
            vaciar();
            txt_Stock.setEditable(false);
            listar();
        }else{
            JOptionPane.showMessageDialog(null, "Termine de llenar los campos", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jlabel_editar_productoMouseClicked

    private void jlabel_eliminar_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_eliminar_productoMouseClicked
        metodos_prod.delete_prod(codigo);
        vaciar();
        listar();
    }//GEN-LAST:event_jlabel_eliminar_productoMouseClicked

    private void TABLA_PRODUCTOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_PRODUCTOSMouseClicked
        txt_Stock.setEditable(true);
        row_select = TABLA_PRODUCTOS.getSelectedRow();
        System.out.println("ROW SELECT:" + row_select);
        codigo = TABLA_PRODUCTOS.getValueAt(row_select, 0).toString();
        txt_nombre.setText(TABLA_PRODUCTOS.getValueAt(row_select, 1).toString());
        jcombo_tipo.setSelectedItem(TABLA_PRODUCTOS.getValueAt(row_select, 2).toString());
        jcombo_Nalmacen.setSelectedItem(TABLA_PRODUCTOS.getValueAt(row_select, 3).toString());
        txt_Stock.setText(TABLA_PRODUCTOS.getValueAt(row_select, 4).toString());
        txt_limite.setText(TABLA_PRODUCTOS.getValueAt(row_select, 5).toString());
    }//GEN-LAST:event_TABLA_PRODUCTOSMouseClicked

    public void Look() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {

        } catch (IllegalAccessException ex) {

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLA_PRODUCTOS;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcombo_Nalmacen;
    private javax.swing.JComboBox<String> jcombo_tipo;
    private javax.swing.JLabel jlabel_agregar_producto;
    private javax.swing.JLabel jlabel_editar_entrada1;
    private javax.swing.JLabel jlabel_editar_entrada2;
    private javax.swing.JLabel jlabel_editar_entrada3;
    private javax.swing.JLabel jlabel_editar_entrada4;
    private javax.swing.JLabel jlabel_editar_entrada5;
    private javax.swing.JLabel jlabel_editar_producto;
    private javax.swing.JLabel jlabel_eliminar_producto;
    private javax.swing.JTextField txt_Stock;
    private javax.swing.JTextField txt_limite;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
    
    
    /*METODOS DE TABLA*/
    
    void listar(){
        TABLA_PRODUCTOS.setModel(metodos_prod.listar_Prod());
    }
    
    void vaciar(){
        txt_limite.setText("");
        txt_nombre.setText("");
        jcombo_tipo.setSelectedItem("Seleccionar");
        jcombo_Nalmacen.setSelectedItem("Seleccionar");    
        txt_Stock.setText("");
    }
}
