/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import BOL.Login;
import SqlMetodos.Conexiones;
import SqlMetodos.Usuarios_sql;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Favio Jeb
 */
public class LoginInit extends javax.swing.JFrame {

    private int xMouse, yMouse;
    Usuarios_sql metodos_login = new Usuarios_sql();
    
    /**
     * Creates new form LoginInit
     */
    public LoginInit() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bg = new javax.swing.JLabel();
        pl_conainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txt_pass = new javax.swing.JPasswordField();
        btn_usuarios = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btn_salir = new javax.swing.JPanel();
        lbl_x = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b2ap3_large_inventories.jpg"))); // NOI18N
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 360, 460));

        pl_conainer.setBackground(new java.awt.Color(255, 255, 255));
        pl_conainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INICIAR SESIÓN");
        pl_conainer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 41, -1, -1));

        txt_user.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        txt_user.setForeground(new java.awt.Color(102, 102, 102));
        txt_user.setBorder(null);
        pl_conainer.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 143, 245, 37));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        pl_conainer.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 186, 245, 12));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contraseña");
        pl_conainer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 204, -1, -1));

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Usuario");
        pl_conainer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 112, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        pl_conainer.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 278, 245, 12));

        txt_pass.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(102, 102, 102));
        txt_pass.setBorder(null);
        pl_conainer.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 235, 245, 37));

        btn_usuarios.setBackground(new java.awt.Color(0, 102, 255));
        btn_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_usuariosMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuarios");

        javax.swing.GroupLayout btn_usuariosLayout = new javax.swing.GroupLayout(btn_usuarios);
        btn_usuarios.setLayout(btn_usuariosLayout);
        btn_usuariosLayout.setHorizontalGroup(
            btn_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btn_usuariosLayout.setVerticalGroup(
            btn_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pl_conainer.add(btn_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 120, 40));

        btn_iniciar.setBackground(new java.awt.Color(0, 102, 255));
        btn_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_iniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_iniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_iniciarMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("      Iniciar");

        javax.swing.GroupLayout btn_iniciarLayout = new javax.swing.GroupLayout(btn_iniciar);
        btn_iniciar.setLayout(btn_iniciarLayout);
        btn_iniciarLayout.setHorizontalGroup(
            btn_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_iniciarLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        btn_iniciarLayout.setVerticalGroup(
            btn_iniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pl_conainer.add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 120, 40));

        getContentPane().add(pl_conainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 350, 430));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salirMouseExited(evt);
            }
        });

        lbl_x.setFont(new java.awt.Font("Malgun Gothic", 0, 18)); // NOI18N
        lbl_x.setForeground(new java.awt.Color(0, 0, 0));
        lbl_x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_x.setText("X");

        javax.swing.GroupLayout btn_salirLayout = new javax.swing.GroupLayout(btn_salir);
        btn_salir.setLayout(btn_salirLayout);
        btn_salirLayout.setHorizontalGroup(
            btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_x, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );
        btn_salirLayout.setVerticalGroup(
            btn_salirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_x, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 673, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen(), y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void btn_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseEntered
        btn_salir.setBackground(Color.red);
        lbl_x.setForeground(Color.white);
    }//GEN-LAST:event_btn_salirMouseEntered

    private void btn_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseExited
        btn_salir.setBackground(Color.white);
        lbl_x.setForeground(Color.black);
    }//GEN-LAST:event_btn_salirMouseExited

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseExited
        btn_usuarios.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_btn_usuariosMouseExited

    private void btn_usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseEntered
        btn_usuarios.setBackground(new Color(0, 68, 170));
    }//GEN-LAST:event_btn_usuariosMouseEntered

    private void btn_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMouseClicked
    String admin = JOptionPane.showInputDialog("Ingrese una contraseña administrativa");

           if(!admin.equals("")){
               if(metodos_login.see_User(admin) == true){
                   User s= new User();
                   s.setVisible(true);
                   dispose();
               }
           }else{
               JOptionPane.showMessageDialog(null, "No termino de llenar el campo", "Error!", JOptionPane.ERROR_MESSAGE);
           }
    }//GEN-LAST:event_btn_usuariosMouseClicked

    private void btn_iniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciarMouseEntered
        btn_iniciar.setBackground(new Color(0, 68, 170));
    }//GEN-LAST:event_btn_iniciarMouseEntered

    private void btn_iniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciarMouseExited
        btn_iniciar.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_btn_iniciarMouseExited

    private void btn_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciarMouseClicked
        System.out.println("LLEHUIE A INMPIRMIR");
        if(!txt_pass.getText().equals("") & !txt_pass.getText().equals("")){
            if(metodos_login.login(txt_user.getText(), txt_pass.getText()) == true){
                Ventana v = new Ventana();
                v.setVisible(true);
                this.dispose();
            }else{
                System.out.println("No se logro establecer la conexion");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Termine de llenar los campos");
        }
    }//GEN-LAST:event_btn_iniciarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginInit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_iniciar;
    private javax.swing.JPanel btn_salir;
    private javax.swing.JPanel btn_usuarios;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_x;
    private javax.swing.JPanel pl_conainer;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
