/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sub_jpanel;

import BOL.Productos;
import BOL.Trabajador;
import SqlMetodos.Entrada_sql;
import java.awt.BorderLayout;
import jpanel.*;
import java.awt.Color;
import static java.lang.String.valueOf;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import BOL.Entrada;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import jdk.nashorn.internal.scripts.JO;

/**
 *
 * @author Julio Ramirez
 */
public class newEntrada_Nueva extends javax.swing.JPanel {
    int width=890, height=630;
    Entrada_sql metodos_entrada = new Entrada_sql();
    String fecha_actual;
    boolean codprod_campo = true, trbj_campo = true;
    /**
     * Creates new form Inicio
     */
    public newEntrada_Nueva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        Jpanel_newSalida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlabel_buscar_salida = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlabel_editar_salida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_buscarcod = new javax.swing.JTextField();
        btn_search_Trbj = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_mostrarAlmacen = new javax.swing.JTextField();
        txt_mostrar_cargo = new javax.swing.JTextField();
        txt_buscarempled = new javax.swing.JTextField();
        btn_searchProd = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_mostrarnombrePord = new javax.swing.JTextField();
        txt_mostrarNameEmpl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jlabel_cancelar = new javax.swing.JLabel();
        jlabel_agregarEntrada = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        txt_mostrarCantidadActual = new javax.swing.JTextField();
        jlabel_lista_salidas = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(890, 660));
        setMinimumSize(new java.awt.Dimension(890, 660));
        setPreferredSize(new java.awt.Dimension(890, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jpanel_newSalida.setBackground(new java.awt.Color(43, 43, 43));
        Jpanel_newSalida.setForeground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Cantidad.png"))); // NOI18N
        jLabel1.setText("INGRESO CANTIDAD");

        jlabel_buscar_salida.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_salida.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_buscar_salida.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editar_entrada.png"))); // NOI18N
        jlabel_buscar_salida.setText("BUSCAR ENTRADAS(FECHA)");
        jlabel_buscar_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_buscar_salidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_buscar_salidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_buscar_salidaMouseExited(evt);
            }
        });

        jlabel_editar_salida.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_editar_salida.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_editar_salida.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_editar_salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Editar_producto.png"))); // NOI18N
        jlabel_editar_salida.setText("EDITAR ENTRADA");
        jlabel_editar_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_editar_salidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_editar_salidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_editar_salidaMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NUEVA ENTRADA DE PRODUCTOS");

        txt_buscarcod.setBackground(new java.awt.Color(43, 43, 43));
        txt_buscarcod.setForeground(new java.awt.Color(153, 153, 153));
        txt_buscarcod.setText("Ingrese el codigo del producto");
        txt_buscarcod.setBorder(null);
        txt_buscarcod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_buscarcodMouseClicked(evt);
            }
        });

        btn_search_Trbj.setBackground(new java.awt.Color(36, 36, 36));
        btn_search_Trbj.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        btn_search_Trbj.setForeground(new java.awt.Color(153, 153, 153));
        btn_search_Trbj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search_TrbjMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buscar_trabajor.png"))); // NOI18N

        javax.swing.GroupLayout btn_search_TrbjLayout = new javax.swing.GroupLayout(btn_search_Trbj);
        btn_search_Trbj.setLayout(btn_search_TrbjLayout);
        btn_search_TrbjLayout.setHorizontalGroup(
            btn_search_TrbjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_search_TrbjLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_search_TrbjLayout.setVerticalGroup(
            btn_search_TrbjLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_search_TrbjLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txt_mostrarAlmacen.setEditable(false);
        txt_mostrarAlmacen.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarAlmacen.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarAlmacen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        txt_mostrar_cargo.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrar_cargo.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrar_cargo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        txt_buscarempled.setBackground(new java.awt.Color(43, 43, 43));
        txt_buscarempled.setForeground(new java.awt.Color(153, 153, 153));
        txt_buscarempled.setText("Ingresa el codigo del empleado");
        txt_buscarempled.setBorder(null);
        txt_buscarempled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_buscarempledMouseClicked(evt);
            }
        });
        txt_buscarempled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarempledActionPerformed(evt);
            }
        });

        btn_searchProd.setBackground(new java.awt.Color(36, 36, 36));
        btn_searchProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        btn_searchProd.setForeground(new java.awt.Color(153, 153, 153));
        btn_searchProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchProdMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buscar_inventario.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_searchProdLayout = new javax.swing.GroupLayout(btn_searchProd);
        btn_searchProd.setLayout(btn_searchProdLayout);
        btn_searchProdLayout.setHorizontalGroup(
            btn_searchProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_searchProdLayout.setVerticalGroup(
            btn_searchProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txt_mostrarnombrePord.setEditable(false);
        txt_mostrarnombrePord.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarnombrePord.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarnombrePord.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        txt_mostrarNameEmpl.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarNameEmpl.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarNameEmpl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new_Entrada.png"))); // NOI18N
        jLabel5.setText("INFORMACION DE ENTRADA");

        txt_cantidad.setBackground(new java.awt.Color(43, 43, 43));
        txt_cantidad.setForeground(new java.awt.Color(153, 153, 153));
        txt_cantidad.setBorder(null);

        jlabel_cancelar.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_cancelar.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_cancelar.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancelar..png"))); // NOI18N
        jlabel_cancelar.setText("CANCELAR ENTRADA");
        jlabel_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_cancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_cancelarMouseExited(evt);
            }
        });

        jlabel_agregarEntrada.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_agregarEntrada.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_agregarEntrada.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_agregarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Agregar_entrada.png"))); // NOI18N
        jlabel_agregarEntrada.setText("AGREGAR ENTRADA");
        jlabel_agregarEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_agregarEntradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_agregarEntradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_agregarEntradaMouseExited(evt);
            }
        });

        txt_mostrarCantidadActual.setEditable(false);
        txt_mostrarCantidadActual.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarCantidadActual.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarCantidadActual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        jlabel_lista_salidas.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_lista_salidas.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_lista_salidas.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_lista_salidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lista.png"))); // NOI18N
        jlabel_lista_salidas.setText("LISTA DE ENTRADAS");
        jlabel_lista_salidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_lista_salidasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_lista_salidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_lista_salidasMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("ALMACEN");

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("ROL");

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("STOCK");

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("PRODUCTO");

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("EMPLEADO");

        javax.swing.GroupLayout Jpanel_newSalidaLayout = new javax.swing.GroupLayout(Jpanel_newSalida);
        Jpanel_newSalida.setLayout(Jpanel_newSalidaLayout);
        Jpanel_newSalidaLayout.setHorizontalGroup(
            Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(jlabel_lista_salidas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(79, 79, 79)
                            .addComponent(jlabel_editar_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112)
                            .addComponent(jlabel_buscar_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                            .addGap(260, 260, 260)
                            .addComponent(jlabel_agregarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(154, 154, 154)
                            .addComponent(jlabel_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Jpanel_newSalidaLayout.createSequentialGroup()
                                    .addComponent(txt_buscarcod, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(btn_searchProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Jpanel_newSalidaLayout.createSequentialGroup()
                                    .addComponent(txt_buscarempled, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(btn_search_Trbj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(64, 64, 64)
                            .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                    .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(txt_mostrarNameEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(80, 80, 80)
                                    .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_mostrar_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_newSalidaLayout.createSequentialGroup()
                                    .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(txt_mostrarnombrePord, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(80, 80, 80)
                                    .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(txt_mostrarCantidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(60, 60, 60)
                                    .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_mostrarAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)))))
                        .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        Jpanel_newSalidaLayout.setVerticalGroup(
            Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel_lista_salidas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_editar_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_buscar_salida))
                .addGap(22, 22, 22)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(3, 3, 3)
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_buscarcod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searchProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mostrarnombrePord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_mostrarAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_mostrarCantidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_buscarempled, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search_Trbj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_mostrarNameEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_mostrar_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_agregarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        fondo.add(Jpanel_newSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel_agregarEntradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregarEntradaMouseExited
        jlabel_agregarEntrada.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_agregarEntradaMouseExited

    private void jlabel_agregarEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregarEntradaMouseEntered
       jlabel_agregarEntrada.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_agregarEntradaMouseEntered

    private void jlabel_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_cancelarMouseExited
         jlabel_cancelar.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_cancelarMouseExited

    private void jlabel_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_cancelarMouseEntered
       jlabel_cancelar.setForeground(Color.red);
    }//GEN-LAST:event_jlabel_cancelarMouseEntered

    private void txt_buscarempledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarempledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarempledActionPerformed

    private void jlabel_editar_salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_salidaMouseExited
        jlabel_editar_salida.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_editar_salidaMouseExited

    private void jlabel_editar_salidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_salidaMouseEntered
        jlabel_editar_salida.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_editar_salidaMouseEntered

    private void jlabel_buscar_salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_salidaMouseExited
        jlabel_buscar_salida.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_buscar_salidaMouseExited

    private void jlabel_buscar_salidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_salidaMouseEntered
        jlabel_buscar_salida.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_buscar_salidaMouseEntered

    private void jlabel_lista_salidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_salidasMouseExited
        jlabel_lista_salidas.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_lista_salidasMouseExited

    private void jlabel_lista_salidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_salidasMouseEntered
        jlabel_lista_salidas.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_lista_salidasMouseEntered

    private void jlabel_lista_salidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_salidasMouseClicked
            Entrada_vista nueva= new Entrada_vista();
            addConatiner(nueva, width, height, Jpanel_newSalida);
    }//GEN-LAST:event_jlabel_lista_salidasMouseClicked

    private void jlabel_editar_salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_salidaMouseClicked
           Entrada_vista nueva= new Entrada_vista();
           addConatiner(nueva, width, height, Jpanel_newSalida);
          JOptionPane.showMessageDialog(null, "Selecciona un elemento de la tabla a editar", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jlabel_editar_salidaMouseClicked

    private void jlabel_buscar_salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_salidaMouseClicked
           newEntrada_Buscar nueva= new newEntrada_Buscar();
           addConatiner(nueva, width, height, Jpanel_newSalida);
    }//GEN-LAST:event_jlabel_buscar_salidaMouseClicked

    private void btn_searchProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchProdMouseClicked
        if(!txt_buscarcod.equals("")){
            Productos p = new Productos();
            /*Busqueda de producto*/
            p = metodos_entrada.search_Prod(txt_buscarcod.getText());
            if(p != null){
                txt_mostrarnombrePord.setText(p.getNombreProducto());
                txt_mostrarAlmacen.setText(valueOf(p.getAlmacen()));
                txt_mostrarCantidadActual.setText(valueOf(p.getCantidad()));
            }else{
                JOptionPane.showMessageDialog(null, "Producto no encontrado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Termine de llenar el campo!","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_searchProdMouseClicked

    private void btn_search_TrbjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search_TrbjMouseClicked
       if(!txt_buscarempled.equals("")){
            Trabajador t = new Trabajador();
            /*Busqueda de trabajador*/
            t = metodos_entrada.search_Trabj(txt_buscarempled.getText());
            if(t != null){
                txt_mostrarNameEmpl.setText(t.getNombres());
                txt_mostrar_cargo.setText(valueOf(t.getCargo()));
            }else{
                JOptionPane.showMessageDialog(null, "Trabajador no encontrado");
                txt_mostrar_cargo.setText("");
            }
        }else{
           JOptionPane.showMessageDialog(null, "Termine de llenar el campo!","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_search_TrbjMouseClicked

    private void jlabel_agregarEntradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregarEntradaMouseClicked
        if(!txt_buscarcod.getText().equals("") & !txt_buscarempled.getText().equals("") & !txt_cantidad.getText().equals("") & !txt_mostrarAlmacen.getText().equals("")
            & !txt_mostrarCantidadActual.getText().equals("") & !txt_mostrarNameEmpl.getText().equals("") & !txt_mostrar_cargo.getText().equals("") & !txt_mostrarnombrePord.getText().equals("")){
            if(!txt_cantidad.getText().equals("0")){
                if(metodos_entrada.cant_limite(txt_buscarcod.getText(), Integer.parseInt(txt_cantidad.getText().toString())) == true){
                    Entrada entrada = new Entrada();
                    entrada.setProducto(txt_buscarcod.getText());
                    entrada.setTrabajador(txt_buscarempled.getText());
                    entrada.setCant_ingreso(Integer.parseInt(txt_cantidad.getText().toString()));
                    entrada.setF_Ingreso(fecha_act());
                    metodos_entrada.add_Sistema_entrada(entrada);
                    JOptionPane.showMessageDialog(null, "Cantidad ingresada con exito","",JOptionPane.INFORMATION_MESSAGE);
                    vaciar();
                    metodos_entrada.listar_entrada();
                }else{
                    JOptionPane.showMessageDialog(null, "la cantidad ingresada sobrepasa el limite!","",JOptionPane.ERROR_MESSAGE);
                    txt_cantidad.setText("");
                }  
            }else{
                JOptionPane.showMessageDialog(null, "No puede ingresar un valor nulo","",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Termine de llenar los campos!","",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_jlabel_agregarEntradaMouseClicked

    private void jlabel_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_cancelarMouseClicked
        vaciar();
    }//GEN-LAST:event_jlabel_cancelarMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txt_buscarcodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarcodMouseClicked
        if(codprod_campo == true){
            txt_buscarcod.setText("");
            codprod_campo = false;
        }
    }//GEN-LAST:event_txt_buscarcodMouseClicked

    private void txt_buscarempledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarempledMouseClicked
       if(trbj_campo == true){
            txt_buscarempled.setText("");
            trbj_campo= false;
        }
    }//GEN-LAST:event_txt_buscarempledMouseClicked

    
    
    
    public void Look() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {

        } catch (IllegalAccessException ex) {

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_newSalida;
    private javax.swing.JPanel btn_searchProd;
    private javax.swing.JPanel btn_search_Trbj;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jlabel_agregarEntrada;
    private javax.swing.JLabel jlabel_buscar_salida;
    private javax.swing.JLabel jlabel_cancelar;
    private javax.swing.JLabel jlabel_editar_salida;
    private javax.swing.JLabel jlabel_lista_salidas;
    private javax.swing.JTextField txt_buscarcod;
    private javax.swing.JTextField txt_buscarempled;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_mostrarAlmacen;
    private javax.swing.JTextField txt_mostrarCantidadActual;
    private javax.swing.JTextField txt_mostrarNameEmpl;
    private javax.swing.JTextField txt_mostrar_cargo;
    private javax.swing.JTextField txt_mostrarnombrePord;
    // End of variables declaration//GEN-END:variables
    public void addConatiner(JPanel p,int width, int height,JPanel c){
        p.setSize(width,height);
        p.setLocation(0,0);
        c.removeAll();
        c.add(p,BorderLayout.CENTER);
        c.revalidate();
        c.repaint();
    }
    
    
    /*OBTENCION DE FECHA ACTUAL*/
    public String fecha_act(){
        Date fecha= new Date();
        SimpleDateFormat formato_fecha = new SimpleDateFormat("yyyy-MM-dd");
        fecha_actual = formato_fecha.format(fecha);
        /**Obtencion de hora actual**/
        LocalTime hora_Actual = LocalTime.now();
        fecha_actual+=" "+hora_Actual;
        return fecha_actual;
    }
    
   
    
    void vaciar(){
        txt_buscarcod.setText("");
        txt_buscarempled.setText("");
        txt_cantidad.setText("");
        txt_mostrarAlmacen.setText("");
        txt_mostrarCantidadActual.setText("");
        txt_mostrarNameEmpl.setText("");
        txt_mostrarnombrePord.setText("");
        txt_mostrar_cargo.setText("");
    }
    

}
