/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sub_jpanel;

import BOL.Entrada;
import BOL.Productos;
import BOL.Trabajador;
import SqlMetodos.Entrada_sql;
import java.awt.BorderLayout;
import jpanel.*;
import java.awt.Color;
import static java.lang.String.valueOf;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Julio Ramirez
 */
public class newEntrada_Editar extends javax.swing.JPanel {
    int width=890, height=630;
    Entrada_sql metodos_entrada = new Entrada_sql();
    Object[] datos_capturados = new Object[3];
    
    public newEntrada_Editar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        Jpanel_nueva_salida = new javax.swing.JPanel();
        jlabel_buscar_entradas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlabel_nueva_entrada = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlabel_lista_entradas = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_buscarcod = new javax.swing.JTextField();
        btn_searchcode = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_mostrarnombrePord = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_mostrarCantidadActual = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_mostrarTipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_mostrarAlmacen = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_buscarempled = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        btn_searchempleado = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_mostrarNameEmpl = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        txt_mostrar_rol = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jday_f_ingreso = new com.toedter.calendar.JDateChooser();
        jlabel_editar_entrada = new javax.swing.JLabel();
        jlabel_cancelarentrada = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(890, 660));
        setMinimumSize(new java.awt.Dimension(890, 660));
        setPreferredSize(new java.awt.Dimension(890, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jpanel_nueva_salida.setBackground(new java.awt.Color(43, 43, 43));
        Jpanel_nueva_salida.setForeground(new java.awt.Color(153, 153, 153));

        jlabel_buscar_entradas.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_entradas.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_buscar_entradas.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_entradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editar_entrada.png"))); // NOI18N
        jlabel_buscar_entradas.setText("BUSCAR ENTRADAS (FECHA)");
        jlabel_buscar_entradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_buscar_entradasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_buscar_entradasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_buscar_entradasMouseExited(evt);
            }
        });

        jlabel_nueva_entrada.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_nueva_entrada.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_nueva_entrada.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_nueva_entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nueva_entrada.png"))); // NOI18N
        jlabel_nueva_entrada.setText("NUEVA ENTRADA");
        jlabel_nueva_entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_nueva_entradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_nueva_entradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_nueva_entradaMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EDITAR ENTRADA DE PRODUCTOS");

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new_Entrada.png"))); // NOI18N
        jLabel5.setText("INFORMACION DE ENTRADA");

        jlabel_lista_entradas.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_lista_entradas.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_lista_entradas.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_lista_entradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lista.png"))); // NOI18N
        jlabel_lista_entradas.setText("LISTA DE ENTRADAS");
        jlabel_lista_entradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_lista_entradasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_lista_entradasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_lista_entradasMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("CODIGO DEL PRODUCTO");

        txt_buscarcod.setBackground(new java.awt.Color(43, 43, 43));
        txt_buscarcod.setForeground(new java.awt.Color(153, 153, 153));
        txt_buscarcod.setBorder(null);

        btn_searchcode.setBackground(new java.awt.Color(36, 36, 36));
        btn_searchcode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        btn_searchcode.setForeground(new java.awt.Color(153, 153, 153));
        btn_searchcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchcodeMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(36, 36, 36));
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buscar_inventario.png"))); // NOI18N

        javax.swing.GroupLayout btn_searchcodeLayout = new javax.swing.GroupLayout(btn_searchcode);
        btn_searchcode.setLayout(btn_searchcodeLayout);
        btn_searchcodeLayout.setHorizontalGroup(
            btn_searchcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btn_searchcodeLayout.setVerticalGroup(
            btn_searchcodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("PRODUCTO");

        txt_mostrarnombrePord.setEditable(false);
        txt_mostrarnombrePord.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarnombrePord.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarnombrePord.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        txt_mostrarnombrePord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_mostrarnombrePordMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("CANTIDAD INGRESO");

        txt_mostrarCantidadActual.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarCantidadActual.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarCantidadActual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("TIPO");

        txt_mostrarTipo.setEditable(false);
        txt_mostrarTipo.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarTipo.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        txt_mostrarTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_mostrarTipoMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("ALMACEN");

        txt_mostrarAlmacen.setEditable(false);
        txt_mostrarAlmacen.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarAlmacen.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarAlmacen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        txt_mostrarAlmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_mostrarAlmacenMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("CODIGO DEL EMPLEADO");

        txt_buscarempled.setBackground(new java.awt.Color(43, 43, 43));
        txt_buscarempled.setForeground(new java.awt.Color(153, 153, 153));
        txt_buscarempled.setBorder(null);
        txt_buscarempled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarempledActionPerformed(evt);
            }
        });

        btn_searchempleado.setBackground(new java.awt.Color(36, 36, 36));
        btn_searchempleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        btn_searchempleado.setForeground(new java.awt.Color(153, 153, 153));
        btn_searchempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchempleadoMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(36, 36, 36));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buscar_trabajor.png"))); // NOI18N

        javax.swing.GroupLayout btn_searchempleadoLayout = new javax.swing.GroupLayout(btn_searchempleado);
        btn_searchempleado.setLayout(btn_searchempleadoLayout);
        btn_searchempleadoLayout.setHorizontalGroup(
            btn_searchempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        btn_searchempleadoLayout.setVerticalGroup(
            btn_searchempleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("EMPLEADO");

        txt_mostrarNameEmpl.setEditable(false);
        txt_mostrarNameEmpl.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarNameEmpl.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarNameEmpl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        txt_mostrarNameEmpl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_mostrarNameEmplMouseClicked(evt);
            }
        });

        txt_mostrar_rol.setEditable(false);
        txt_mostrar_rol.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrar_rol.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrar_rol.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        txt_mostrar_rol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_mostrar_rolMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("ROL");

        jLabel15.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fehca_registro.png"))); // NOI18N
        jLabel15.setText("FECHA DE REGISTRO");

        jday_f_ingreso.setBackground(new java.awt.Color(43, 43, 43));
        jday_f_ingreso.setForeground(new java.awt.Color(153, 153, 153));

        jlabel_editar_entrada.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_editar_entrada.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_editar_entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        jlabel_editar_entrada.setText("EDITAR ENTRADA");
        jlabel_editar_entrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_editar_entradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_editar_entradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_editar_entradaMouseExited(evt);
            }
        });

        jlabel_cancelarentrada.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_cancelarentrada.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_cancelarentrada.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_cancelarentrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancelar..png"))); // NOI18N
        jlabel_cancelarentrada.setText("ELIMINAR ENTRADA");
        jlabel_cancelarentrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_cancelarentradaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_cancelarentradaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_cancelarentradaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Jpanel_nueva_salidaLayout = new javax.swing.GroupLayout(Jpanel_nueva_salida);
        Jpanel_nueva_salida.setLayout(Jpanel_nueva_salidaLayout);
        Jpanel_nueva_salidaLayout.setHorizontalGroup(
            Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(jlabel_lista_entradas)
                            .addGap(111, 111, 111)
                            .addComponent(jlabel_nueva_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112)
                            .addComponent(jlabel_buscar_entradas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jday_f_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(136, 136, 136))
                                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_buscarcod, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(78, 78, 78)))
                                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                        .addGap(158, 158, 158)
                                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_mostrar_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(txt_mostrarnombrePord, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel7)))
                                .addGap(0, 235, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_nueva_salidaLayout.createSequentialGroup()
                                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_buscarempled, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                                .addComponent(btn_searchempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_mostrarNameEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(298, 346, Short.MAX_VALUE))
                                            .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                                        .addGap(224, 224, 224)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(btn_searchcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(txt_mostrarCantidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Jpanel_nueva_salidaLayout.createSequentialGroup()
                                                                    .addGap(224, 224, 224)
                                                                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_mostrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel14))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_mostrarAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_nueva_salidaLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jlabel_cancelarentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9))))
                                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jlabel_editar_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(47, 47, 47))))))
        );
        Jpanel_nueva_salidaLayout.setVerticalGroup(
            Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel_lista_entradas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_nueva_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_buscar_entradas))
                .addGap(22, 22, 22)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel14))
                                .addGap(3, 3, 3)
                                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_buscarcod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mostrarnombrePord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mostrarCantidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mostrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mostrarAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator10)
                                    .addComponent(jSeparator8)
                                    .addComponent(jSeparator3)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7))
                        .addGap(3, 3, 3)
                        .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_buscarempled, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mostrarNameEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mostrar_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                        .addComponent(btn_searchcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_searchempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_nueva_salidaLayout.createSequentialGroup()
                        .addComponent(jday_f_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_nueva_salidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabel_editar_entrada)
                        .addComponent(jlabel_cancelarentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fondo.add(Jpanel_nueva_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel_nueva_entradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_entradaMouseExited
        jlabel_nueva_entrada.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_nueva_entradaMouseExited

    private void jlabel_nueva_entradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_entradaMouseEntered
        jlabel_nueva_entrada.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_nueva_entradaMouseEntered

    private void jlabel_buscar_entradasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_entradasMouseExited
        jlabel_buscar_entradas.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_buscar_entradasMouseExited

    private void jlabel_buscar_entradasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_entradasMouseEntered
        jlabel_buscar_entradas.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_buscar_entradasMouseEntered

    private void jlabel_lista_entradasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_entradasMouseExited
        jlabel_lista_entradas.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_lista_entradasMouseExited

    private void jlabel_lista_entradasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_entradasMouseEntered
        jlabel_lista_entradas.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_lista_entradasMouseEntered

    private void jlabel_lista_entradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_entradasMouseClicked
            Entrada_vista nueva= new Entrada_vista();
            addConatiner(nueva, width, height, Jpanel_nueva_salida);
    }//GEN-LAST:event_jlabel_lista_entradasMouseClicked

    private void jlabel_nueva_entradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_entradaMouseClicked
          newEntrada_Nueva nueva= new newEntrada_Nueva();
          addConatiner(nueva, width, height, Jpanel_nueva_salida);
    }//GEN-LAST:event_jlabel_nueva_entradaMouseClicked

    private void jlabel_buscar_entradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_entradasMouseClicked
          newEntrada_Buscar nueva= new newEntrada_Buscar();
          addConatiner(nueva, width, height, Jpanel_nueva_salida);
    }//GEN-LAST:event_jlabel_buscar_entradasMouseClicked

    private void txt_buscarempledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarempledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarempledActionPerformed

    private void jlabel_editar_entradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_entradaMouseEntered
        jlabel_editar_entrada.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_editar_entradaMouseEntered

    private void jlabel_editar_entradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_entradaMouseExited
        jlabel_editar_entrada.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_editar_entradaMouseExited

    private void jlabel_cancelarentradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_cancelarentradaMouseEntered
        jlabel_cancelarentrada.setForeground(Color.red);
    }//GEN-LAST:event_jlabel_cancelarentradaMouseEntered

    private void jlabel_cancelarentradaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_cancelarentradaMouseExited
        jlabel_cancelarentrada.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_cancelarentradaMouseExited

    private void txt_mostrarnombrePordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_mostrarnombrePordMouseClicked
       JOptionPane.showMessageDialog(null, "Si desea cambiar los datos dirijase al apartado de Productos");
    }//GEN-LAST:event_txt_mostrarnombrePordMouseClicked

    private void txt_mostrarTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_mostrarTipoMouseClicked
        JOptionPane.showMessageDialog(null, "Si desea cambiar los datos dirijase al apartado de Productos");
    }//GEN-LAST:event_txt_mostrarTipoMouseClicked

    private void txt_mostrarAlmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_mostrarAlmacenMouseClicked
        JOptionPane.showMessageDialog(null, "Si desea cambiar los datos dirijase al apartado de Productos");
    }//GEN-LAST:event_txt_mostrarAlmacenMouseClicked

    private void txt_mostrarNameEmplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_mostrarNameEmplMouseClicked
       JOptionPane.showMessageDialog(null, "Si desea cambiar los datos dirijase al apartado de Trabajadores");
    }//GEN-LAST:event_txt_mostrarNameEmplMouseClicked

    private void txt_mostrar_rolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_mostrar_rolMouseClicked
        JOptionPane.showMessageDialog(null, "Si desea cambiar los datos dirijase al apartado de Trabajadores");
    }//GEN-LAST:event_txt_mostrar_rolMouseClicked

    private void jlabel_editar_entradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_entradaMouseClicked
        if(!txt_buscarcod.getText().equals("") & !txt_buscarempled.getText().equals("") & !txt_mostrarAlmacen.equals("") & !txt_mostrarCantidadActual.equals("") & !txt_mostrarNameEmpl.equals("")
                & !txt_mostrarTipo.equals("") & !txt_mostrar_rol.getText().equals("") & !txt_mostrarnombrePord.getText().equals("") & jday_f_ingreso.getDate() != null){
            /*Captura de datos actuales*/
            Object[] ob_nuevos = new Object[3];
            
            Productos p_nuevo = new Productos();
            p_nuevo.setCodigoProducto(txt_buscarcod.getText());
            
            Trabajador t_nuevo = new Trabajador();
            t_nuevo.setId(txt_buscarempled.getText());
            ob_nuevos[1] = t_nuevo;
            
            Entrada e_nuevo = new Entrada();
            e_nuevo.setCant_ingreso(Integer.parseInt(txt_mostrarCantidadActual.getText()));
            e_nuevo.setF_Ingreso(fecha_act(jday_f_ingreso.getDate()));
            
            
            
            
            Entrada entrad_antigua = (Entrada) datos_capturados[2] ;
            Productos prod_antigua = (Productos) datos_capturados[0];
            if(txt_buscarcod.getText().equals(prod_antigua.getCodigoProducto())){
                System.out.println("Los codigo son iguales");
                int update_t = (prod_antigua.getCantidad() - entrad_antigua.getCant_ingreso()) + Integer.parseInt(txt_mostrarCantidadActual.getText());
                p_nuevo.setCantidad(update_t);
                System.out.println("Total actualizado: " +update_t);
                if(update_t <= prod_antigua.getLimite()){
                    ob_nuevos[0] = p_nuevo;
                    ob_nuevos[2] = e_nuevo;
                    metodos_entrada.update_CodEquals(datos_capturados, ob_nuevos);
                    JOptionPane.showMessageDialog(null, "Actualizacion exitosa!","", JOptionPane.INFORMATION_MESSAGE);
                    Entrada_vista nueva= new Entrada_vista();
                    addConatiner(nueva, width, height, Jpanel_nueva_salida);
                }else{
                    JOptionPane.showMessageDialog(null, "La cantidad ingresada sobrepasa el limite","", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                if(metodos_entrada.cant_limite(txt_buscarcod.getText(), Integer.parseInt(txt_mostrarCantidadActual.getText())) == true ){  
                    int cant_prod = (prod_antigua.getCantidad() - entrad_antigua.getCant_ingreso());
                    System.out.println(prod_antigua.getCantidad() +"  "+ entrad_antigua.getCant_ingreso() +" CANTIDAD QUITADA:" + cant_prod);
                    /*ACTUALISADO DE DATOS, DEL DATO ANTIGUO*/
                    Productos p_antiguo = (Productos) datos_capturados[0];
                    p_antiguo.setCantidad(cant_prod);
                    datos_capturados[0] = p_antiguo;
                    
                    ob_nuevos[0] = p_nuevo;
                    ob_nuevos[2] = e_nuevo;
                    metodos_entrada.update_CodDiferent(datos_capturados, ob_nuevos);
                    JOptionPane.showMessageDialog(null, "Actualizacion exitosa!","", JOptionPane.INFORMATION_MESSAGE);
                    Entrada_vista nueva= new Entrada_vista();
                    addConatiner(nueva, width, height, Jpanel_nueva_salida);
                }else{
                   JOptionPane.showMessageDialog(null, "La cantidad ingresada sobrepasa el limite","", JOptionPane.ERROR_MESSAGE);
                }
                
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Termine de llenar los campos", "", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jlabel_editar_entradaMouseClicked

    private void jlabel_cancelarentradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_cancelarentradaMouseClicked
            Entrada entrad_antigua = (Entrada) datos_capturados[2] ;
            Productos prod_antigua = (Productos) datos_capturados[0];
        
            int cant_prod = (prod_antigua.getCantidad() - entrad_antigua.getCant_ingreso());
            /*ACTUALISADO DE DATOS, DEL DATO ANTIGUO*/
            Productos p_antiguo = (Productos) datos_capturados[0];
            p_antiguo.setCantidad(cant_prod);
            datos_capturados[0] = p_antiguo;
        
            metodos_entrada.delete_Entrad(datos_capturados);
            
            JOptionPane.showMessageDialog(null, "Entrada eliminada!","", JOptionPane.INFORMATION_MESSAGE);
            Entrada_vista nueva= new Entrada_vista();
            addConatiner(nueva, width, height, Jpanel_nueva_salida);
    }//GEN-LAST:event_jlabel_cancelarentradaMouseClicked

    private void btn_searchcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchcodeMouseClicked
        if(!txt_buscarcod.equals("")){
            Productos p = new Productos();
            /*Busqueda de producto*/
            p = metodos_entrada.search_Prod(txt_buscarcod.getText());
            if(p != null){
                txt_mostrarnombrePord.setText(p.getNombreProducto());
                txt_mostrarAlmacen.setText(valueOf(p.getAlmacen()));
                txt_mostrarCantidadActual.setText("");
                txt_mostrarTipo.setText(p.getTipo());
            }else{
                JOptionPane.showMessageDialog(null, "Producto no encontrado");
                txt_buscarcod.setText("");
                txt_mostrarCantidadActual.setText("");
                txt_mostrarAlmacen.setText("");
                txt_mostrarTipo.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Termine de llenar el campo!","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_searchcodeMouseClicked

    private void btn_searchempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchempleadoMouseClicked
        if(!txt_buscarempled.equals("")){
            Trabajador t = new Trabajador();
            /*Busqueda de trabajador*/
            t = metodos_entrada.search_Trabj(txt_buscarempled.getText());
            if(t != null){
                txt_mostrarNameEmpl.setText(t.getNombres());
                txt_mostrar_rol.setText(valueOf(t.getCargo()));
            }else{
                JOptionPane.showMessageDialog(null, "Trabajador no encontrado");
                txt_mostrar_rol.setText("");
                txt_mostrarNameEmpl.setText("");
            }
        }else{
           JOptionPane.showMessageDialog(null, "Termine de llenar el campo!","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_searchempleadoMouseClicked

    
    
    
    public void Look() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {

        } catch (IllegalAccessException ex) {

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_nueva_salida;
    private javax.swing.JPanel btn_searchcode;
    private javax.swing.JPanel btn_searchempleado;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private com.toedter.calendar.JDateChooser jday_f_ingreso;
    private javax.swing.JLabel jlabel_buscar_entradas;
    private javax.swing.JLabel jlabel_cancelarentrada;
    private javax.swing.JLabel jlabel_editar_entrada;
    private javax.swing.JLabel jlabel_lista_entradas;
    private javax.swing.JLabel jlabel_nueva_entrada;
    private javax.swing.JTextField txt_buscarcod;
    private javax.swing.JTextField txt_buscarempled;
    private javax.swing.JTextField txt_mostrarAlmacen;
    private javax.swing.JTextField txt_mostrarCantidadActual;
    private javax.swing.JTextField txt_mostrarNameEmpl;
    private javax.swing.JTextField txt_mostrarTipo;
    private javax.swing.JTextField txt_mostrar_rol;
    private javax.swing.JTextField txt_mostrarnombrePord;
    // End of variables declaration//GEN-END:variables
    public void addConatiner(JPanel p,int width, int height,JPanel c){
        p.setSize(width,height);
        p.setLocation(0,0);
        c.removeAll();
        c.add(p,BorderLayout.CENTER);
        c.revalidate();
        c.repaint();
    }
    
    
    /*Captura de datos*/
    
    public void captura_Datos(String codigo_entrada, Date fecha_ingreso){
       datos_capturados = metodos_entrada.obtencion_Datos(codigo_entrada);
       Productos p = (Productos) datos_capturados[0];
       Trabajador t =  (Trabajador) datos_capturados[1];
       Entrada e = (Entrada) datos_capturados[2];
       /*Datos del producto y entrada capturados*/
       txt_buscarcod.setText(p.getCodigoProducto());
       txt_mostrarnombrePord.setText(p.getNombreProducto());
       txt_mostrarAlmacen.setText(valueOf(p.getAlmacen()));
       txt_mostrarCantidadActual.setText(valueOf(e.getCant_ingreso()));
       txt_mostrarTipo.setText(p.getTipo());

       /*Datos del trabajador capturados*/
       txt_buscarempled.setText(t.getId());
       txt_mostrarNameEmpl.setText(t.getNombres());
       txt_mostrar_rol.setText(t.getCargo());
       
       /*Fecha de ingreso capturada*/
       jday_f_ingreso.setDate(fecha_ingreso);
       
    }
    
    /*OBTENCION DE FECHA ACTUAL*/
    public String fecha_act(Date date){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = sdf.format(date);
        System.out.println("FECHA:" + fecha);
        /**Obtencion de hora actual**/
        LocalTime hora_Actual = LocalTime.now();
        fecha+=" "+hora_Actual;
        return fecha;
    }
}
