/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sub_jpanel;

import BOL.Entrada;
import BOL.Productos;
import BOL.Salida;
import BOL.Trabajador;
import SqlMetodos.Salida_sql;
import java.awt.BorderLayout;
import jpanel.*;
import java.awt.Color;
import static java.lang.String.valueOf;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Julio Ramirez
 */
public class Salida_Editar extends javax.swing.JPanel {
    int width=890, height=630;
    Salida_sql metodos_salida= new Salida_sql();
    Object[] datos_capturados = new Object[3];
    
    
    /**
     * Creates new form Inicio
     */
    public Salida_Editar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        Jpanel_newSalida = new javax.swing.JPanel();
        jlabel_buscar_salida = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlabel_nueva_salida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlabel_lista_salidas = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_buscarcod = new javax.swing.JTextField();
        btn_seachProd = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_mostrarnombrePord = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_mostrarCantidadActual = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_mostrarTipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_mostrarAlmacen = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_buscarempled = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        btn_searchEmplead = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_mostrarNameEmpl = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        txt_mostrar_rol = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jday_salida = new com.toedter.calendar.JDateChooser();
        jlabel_agregarprod = new javax.swing.JLabel();
        jlabel_cancelar1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(890, 660));
        setMinimumSize(new java.awt.Dimension(890, 660));
        setPreferredSize(new java.awt.Dimension(890, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jpanel_newSalida.setBackground(new java.awt.Color(43, 43, 43));
        Jpanel_newSalida.setForeground(new java.awt.Color(153, 153, 153));

        jlabel_buscar_salida.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_salida.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_buscar_salida.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editar_entrada.png"))); // NOI18N
        jlabel_buscar_salida.setText("BUSCAR SALIDAS (FECHA)");
        jlabel_buscar_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_buscar_salidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_buscar_salidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_buscar_salidaMouseExited(evt);
            }
        });

        jlabel_nueva_salida.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_nueva_salida.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_nueva_salida.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_nueva_salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nueva_entrada.png"))); // NOI18N
        jlabel_nueva_salida.setText("NUEVA SALIDA");
        jlabel_nueva_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_nueva_salidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_nueva_salidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_nueva_salidaMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EDITAR SALIDA DE PRODUCTOS");

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nueva_salida.png"))); // NOI18N
        jLabel5.setText("INFORMACION DE SALIDA");

        jlabel_lista_salidas.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_lista_salidas.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_lista_salidas.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_lista_salidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lista.png"))); // NOI18N
        jlabel_lista_salidas.setText("LISTA DE SALIDAS");
        jlabel_lista_salidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_lista_salidasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_lista_salidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_lista_salidasMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("CODIGO DEL PRODUCTO");

        txt_buscarcod.setBackground(new java.awt.Color(43, 43, 43));
        txt_buscarcod.setForeground(new java.awt.Color(153, 153, 153));
        txt_buscarcod.setBorder(null);

        btn_seachProd.setBackground(new java.awt.Color(36, 36, 36));
        btn_seachProd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        btn_seachProd.setForeground(new java.awt.Color(153, 153, 153));
        btn_seachProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seachProdMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(36, 36, 36));
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buscar_inventario.png"))); // NOI18N

        javax.swing.GroupLayout btn_seachProdLayout = new javax.swing.GroupLayout(btn_seachProd);
        btn_seachProd.setLayout(btn_seachProdLayout);
        btn_seachProdLayout.setHorizontalGroup(
            btn_seachProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_seachProdLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_seachProdLayout.setVerticalGroup(
            btn_seachProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("PRODUCTO");

        txt_mostrarnombrePord.setEditable(false);
        txt_mostrarnombrePord.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarnombrePord.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarnombrePord.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("EXTRACCION");

        txt_mostrarCantidadActual.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarCantidadActual.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarCantidadActual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("TIPO");

        txt_mostrarTipo.setEditable(false);
        txt_mostrarTipo.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarTipo.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("ALMACEN");

        txt_mostrarAlmacen.setEditable(false);
        txt_mostrarAlmacen.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarAlmacen.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarAlmacen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        jLabel12.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("CODIGO DEL EMPLEADO");

        txt_buscarempled.setBackground(new java.awt.Color(43, 43, 43));
        txt_buscarempled.setForeground(new java.awt.Color(153, 153, 153));
        txt_buscarempled.setBorder(null);
        txt_buscarempled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarempledActionPerformed(evt);
            }
        });

        btn_searchEmplead.setBackground(new java.awt.Color(36, 36, 36));
        btn_searchEmplead.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        btn_searchEmplead.setForeground(new java.awt.Color(153, 153, 153));
        btn_searchEmplead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchEmpleadMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(36, 36, 36));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buscar_trabajor.png"))); // NOI18N

        javax.swing.GroupLayout btn_searchEmpleadLayout = new javax.swing.GroupLayout(btn_searchEmplead);
        btn_searchEmplead.setLayout(btn_searchEmpleadLayout);
        btn_searchEmpleadLayout.setHorizontalGroup(
            btn_searchEmpleadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_searchEmpleadLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_searchEmpleadLayout.setVerticalGroup(
            btn_searchEmpleadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("EMPLEADO");

        txt_mostrarNameEmpl.setEditable(false);
        txt_mostrarNameEmpl.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrarNameEmpl.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrarNameEmpl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        txt_mostrar_rol.setEditable(false);
        txt_mostrar_rol.setBackground(new java.awt.Color(36, 36, 36));
        txt_mostrar_rol.setForeground(new java.awt.Color(153, 153, 153));
        txt_mostrar_rol.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("ROL");

        jLabel15.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fehca_registro.png"))); // NOI18N
        jLabel15.setText("FECHA DE SALIDA");

        jday_salida.setBackground(new java.awt.Color(43, 43, 43));
        jday_salida.setForeground(new java.awt.Color(153, 153, 153));

        jlabel_agregarprod.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_agregarprod.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_agregarprod.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_agregarprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        jlabel_agregarprod.setText("EDITAR SALIDA");
        jlabel_agregarprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_agregarprodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_agregarprodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_agregarprodMouseExited(evt);
            }
        });

        jlabel_cancelar1.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_cancelar1.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_cancelar1.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancelar..png"))); // NOI18N
        jlabel_cancelar1.setText("ELIMINAR SALIDA");
        jlabel_cancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_cancelar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_cancelar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_cancelar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout Jpanel_newSalidaLayout = new javax.swing.GroupLayout(Jpanel_newSalida);
        Jpanel_newSalida.setLayout(Jpanel_newSalidaLayout);
        Jpanel_newSalidaLayout.setHorizontalGroup(
            Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jlabel_lista_salidas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(jlabel_nueva_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(jlabel_buscar_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jday_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))
                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                        .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel13))
                                                .addGap(136, 136, 136))
                                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_buscarcod, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(78, 78, 78)))
                                        .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                                .addGap(158, 158, 158)
                                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_mostrar_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(txt_mostrarnombrePord, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9))
                                                .addGap(28, 28, 28)
                                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8)
                                                        .addComponent(txt_mostrarCantidadActual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                        .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_buscarempled, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                                .addComponent(btn_searchEmplead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_mostrarNameEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(298, 298, 298))
                                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                                .addComponent(btn_seachProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(300, 300, 300)
                                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                                        .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txt_mostrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel14))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                                        .addGap(123, 123, 123)
                                                        .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txt_mostrarAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_newSalidaLayout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jlabel_agregarprod, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlabel_cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)))))))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        Jpanel_newSalidaLayout.setVerticalGroup(
            Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel_lista_salidas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_nueva_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_buscar_salida))
                .addGap(22, 22, 22)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                        .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel14))
                                .addGap(3, 3, 3)
                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_buscarcod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mostrarnombrePord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mostrarCantidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mostrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mostrarAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator10)
                                    .addComponent(jSeparator8)
                                    .addComponent(jSeparator3)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7))
                        .addGap(3, 3, 3)
                        .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_buscarempled, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mostrarNameEmpl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mostrar_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                        .addComponent(btn_seachProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btn_searchEmplead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jpanel_newSalidaLayout.createSequentialGroup()
                        .addComponent(jday_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jpanel_newSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlabel_agregarprod)
                        .addComponent(jlabel_cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        fondo.add(Jpanel_newSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 660));

        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel_nueva_salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_salidaMouseExited
        jlabel_nueva_salida.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_nueva_salidaMouseExited

    private void jlabel_nueva_salidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_salidaMouseEntered
        jlabel_nueva_salida.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_nueva_salidaMouseEntered

    private void jlabel_buscar_salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_salidaMouseExited
        jlabel_buscar_salida.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_buscar_salidaMouseExited

    private void jlabel_buscar_salidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_salidaMouseEntered
        jlabel_buscar_salida.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_buscar_salidaMouseEntered

    private void jlabel_lista_salidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_salidasMouseExited
        jlabel_lista_salidas.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_lista_salidasMouseExited

    private void jlabel_lista_salidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_salidasMouseEntered
        jlabel_lista_salidas.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_lista_salidasMouseEntered

    private void jlabel_lista_salidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_salidasMouseClicked
        Salida_vista nueva= new Salida_vista();
        addConatiner(nueva, width, height, Jpanel_newSalida);
    }//GEN-LAST:event_jlabel_lista_salidasMouseClicked

    private void jlabel_nueva_salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_salidaMouseClicked
          Salida_Nueva nueva= new Salida_Nueva();
          addConatiner(nueva, width, height, Jpanel_newSalida);
    }//GEN-LAST:event_jlabel_nueva_salidaMouseClicked

    private void jlabel_buscar_salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_salidaMouseClicked
          Salida_Buscar nueva= new Salida_Buscar();
          addConatiner(nueva, width, height, Jpanel_newSalida);
    }//GEN-LAST:event_jlabel_buscar_salidaMouseClicked

    private void txt_buscarempledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarempledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarempledActionPerformed

    private void jlabel_agregarprodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregarprodMouseEntered
        jlabel_agregarprod.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_agregarprodMouseEntered

    private void jlabel_agregarprodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregarprodMouseExited
        jlabel_agregarprod.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_agregarprodMouseExited

    private void jlabel_cancelar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_cancelar1MouseEntered
        jlabel_cancelar1.setForeground(Color.red);
    }//GEN-LAST:event_jlabel_cancelar1MouseEntered

    private void jlabel_cancelar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_cancelar1MouseExited
        jlabel_cancelar1.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_cancelar1MouseExited

    private void btn_seachProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seachProdMouseClicked
        if(!txt_buscarcod.equals("")){
            Productos p = new Productos();
            /*Busqueda de producto*/
            p = metodos_salida.search_Prod(txt_buscarcod.getText());
            if(p != null){
                txt_mostrarnombrePord.setText(p.getNombreProducto());
                txt_mostrarAlmacen.setText(valueOf(p.getAlmacen()));
                txt_mostrarCantidadActual.setText("");
                txt_mostrarTipo.setText(p.getTipo());
            }else{
                JOptionPane.showMessageDialog(null, "Producto no encontrado");
                txt_buscarcod.setText("");
                txt_mostrarCantidadActual.setText("");
                txt_mostrarAlmacen.setText("");
                txt_mostrarTipo.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Termine de llenar el campo!","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_seachProdMouseClicked

    private void btn_searchEmpleadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchEmpleadMouseClicked
        if(!txt_buscarempled.equals("")){
            Trabajador t = new Trabajador();
            /*Busqueda de trabajador*/
            t = metodos_salida.search_Trabj(txt_buscarempled.getText());
            if(t != null){
                txt_mostrarNameEmpl.setText(t.getNombres());
                txt_mostrar_rol.setText(valueOf(t.getCargo()));
            }else{
                JOptionPane.showMessageDialog(null, "Trabajador no encontrado");
                txt_mostrar_rol.setText("");
                txt_mostrarNameEmpl.setText("");
            }
        }else{
           JOptionPane.showMessageDialog(null, "Termine de llenar el campo!","",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_searchEmpleadMouseClicked

    private void jlabel_agregarprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_agregarprodMouseClicked
         if(!txt_buscarcod.getText().equals("") & !txt_buscarempled.getText().equals("") & !txt_mostrarAlmacen.equals("") & !txt_mostrarCantidadActual.equals("") & !txt_mostrarNameEmpl.equals("")
                & !txt_mostrarTipo.equals("") & !txt_mostrar_rol.getText().equals("") & !txt_mostrarnombrePord.getText().equals("") & jday_salida.getDate() != null){
            /*Captura de datos actuales*/
            Object[] ob_nuevos = new Object[3];
            
            Productos p_nuevo = new Productos();
            p_nuevo.setCodigoProducto(txt_buscarcod.getText());
            
            Trabajador t_nuevo = new Trabajador();
            t_nuevo.setId(txt_buscarempled.getText());
            ob_nuevos[1] = t_nuevo;
            
            Salida s_nuevo = new Salida();
            s_nuevo.setCant_ingreso(Integer.parseInt(txt_mostrarCantidadActual.getText()));
            s_nuevo.setF_Salida(fecha_act(jday_salida.getDate()));
            

            Salida salid_antigua = (Salida) datos_capturados[2] ;
            Productos prod_antigua = (Productos) datos_capturados[0];
            if(txt_buscarcod.getText().equals(prod_antigua.getCodigoProducto())){
                System.out.println("Los codigo son iguales");
                int update_t = (prod_antigua.getCantidad() + salid_antigua.getCant_ingreso()) - Integer.parseInt(txt_mostrarCantidadActual.getText());
                p_nuevo.setCantidad(update_t);
                System.out.println("Total actualizado: " +update_t);
                if(update_t >=0){
                    ob_nuevos[0] = p_nuevo;
                    ob_nuevos[2] = s_nuevo;
                    metodos_salida.update_CodEquals(datos_capturados, ob_nuevos);
                    JOptionPane.showMessageDialog(null, "Actualizacion exitosa!","", JOptionPane.INFORMATION_MESSAGE);
                    Salida_vista nueva= new Salida_vista();
                    addConatiner(nueva, width, height, Jpanel_newSalida);
                }else{
                    JOptionPane.showMessageDialog(null, "La cantidad extraida sobrepasa el limite","", JOptionPane.ERROR_MESSAGE);
                    txt_mostrarCantidadActual.setText("");
                }
            }else{
                
                if(metodos_salida.cant_limite(txt_buscarcod.getText(), Integer.parseInt(txt_mostrarCantidadActual.getText())) == true ){  
                    int cant_prod = (prod_antigua.getCantidad() + salid_antigua.getCant_ingreso());
                    System.out.println(prod_antigua.getCantidad() +"  "+ salid_antigua.getCant_ingreso() +" CANTIDAD QUITADA:" + cant_prod);
                    /*ACTUALISADO DE DATOS, DEL DATO ANTIGUO*/
                    Productos p_antiguo = (Productos) datos_capturados[0];
                    p_antiguo.setCantidad(cant_prod);
                    datos_capturados[0] = p_antiguo;
  
                    ob_nuevos[0] = p_nuevo;
                    ob_nuevos[2] = s_nuevo;
                    metodos_salida.update_CodDiferent(datos_capturados, ob_nuevos);
                    JOptionPane.showMessageDialog(null, "Actualizacion exitosa!","", JOptionPane.INFORMATION_MESSAGE);
                    Salida_vista nueva= new Salida_vista();
                    addConatiner(nueva, width, height, Jpanel_newSalida);
                }else{
                   JOptionPane.showMessageDialog(null, "La cantidad extraida sobrepasa el limite","", JOptionPane.ERROR_MESSAGE);
                    txt_mostrarCantidadActual.setText("");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Termine de llenar los campos", "", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jlabel_agregarprodMouseClicked

    private void jlabel_cancelar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_cancelar1MouseClicked
            Salida salida_antigua = (Salida) datos_capturados[2] ;
            Productos prod_antigua = (Productos) datos_capturados[0];
        
            int cant_prod = (prod_antigua.getCantidad() + salida_antigua.getCant_ingreso());
            /*ACTUALISADO DE DATOS, DEL DATO ANTIGUO*/
            Productos p_antiguo = (Productos) datos_capturados[0];
            p_antiguo.setCantidad(cant_prod);
            datos_capturados[0] = p_antiguo;
        
            metodos_salida.delete_Salida(datos_capturados);
            
            JOptionPane.showMessageDialog(null, "Salida eliminada!","", JOptionPane.INFORMATION_MESSAGE);
            Salida_vista nueva= new Salida_vista();
            addConatiner(nueva, width, height, Jpanel_newSalida);
    }//GEN-LAST:event_jlabel_cancelar1MouseClicked

    
    
    
    public void Look() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {

        } catch (IllegalAccessException ex) {

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_newSalida;
    private javax.swing.JPanel btn_seachProd;
    private javax.swing.JPanel btn_searchEmplead;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private com.toedter.calendar.JDateChooser jday_salida;
    private javax.swing.JLabel jlabel_agregarprod;
    private javax.swing.JLabel jlabel_buscar_salida;
    private javax.swing.JLabel jlabel_cancelar1;
    private javax.swing.JLabel jlabel_lista_salidas;
    private javax.swing.JLabel jlabel_nueva_salida;
    private javax.swing.JTextField txt_buscarcod;
    private javax.swing.JTextField txt_buscarempled;
    private javax.swing.JTextField txt_mostrarAlmacen;
    private javax.swing.JTextField txt_mostrarCantidadActual;
    private javax.swing.JTextField txt_mostrarNameEmpl;
    private javax.swing.JTextField txt_mostrarTipo;
    private javax.swing.JTextField txt_mostrar_rol;
    private javax.swing.JTextField txt_mostrarnombrePord;
    // End of variables declaration//GEN-END:variables
    public void addConatiner(JPanel p,int width, int height,JPanel c){
        p.setSize(width,height);
        p.setLocation(0,0);
        c.removeAll();
        c.add(p,BorderLayout.CENTER);
        c.revalidate();
        c.repaint();
    }
    
    
    public void captura_Datos(String codigo_entrada, Date fecha_ingreso){
       datos_capturados = metodos_salida.obtencion_Datos(codigo_entrada);
       Productos p = (Productos) datos_capturados[0];
       Trabajador t =  (Trabajador) datos_capturados[1];
       Salida e = (Salida) datos_capturados[2];
       /*Datos del producto y entrada capturados*/
       txt_buscarcod.setText(p.getCodigoProducto());
       txt_mostrarnombrePord.setText(p.getNombreProducto());
       txt_mostrarAlmacen.setText(valueOf(p.getAlmacen()));
       txt_mostrarCantidadActual.setText(valueOf(e.getCant_ingreso()));
       txt_mostrarTipo.setText(p.getTipo());

       /*Datos del trabajador capturados*/
       txt_buscarempled.setText(t.getId());
       txt_mostrarNameEmpl.setText(t.getNombres());
       txt_mostrar_rol.setText(t.getCargo());

       
       /*Fecha de ingreso capturada*/
       jday_salida.setDate(fecha_ingreso);
       
    }
    
    
    
     /*OBTENCION DE FECHA ACTUAL*/
     public String fecha_act(Date date){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = sdf.format(date);
        System.out.println("FECHA:" + fecha);
        /**Obtencion de hora actual**/
        LocalTime hora_Actual = LocalTime.now();
        fecha+=" "+hora_Actual;
        return fecha;
    }
}
