/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sub_jpanel;

import SqlMetodos.Salida_sql;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import jpanel.Salida_vista;

/**
 *
 * @author Julio Ramirez
 */
public class Salida_Buscar extends javax.swing.JPanel {
     int width=890, height=630;
     Salida_sql metodos_salida= new Salida_sql();
    /**
     * Creates new form Inicio
     */
    public Salida_Buscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        Jpanel_fondo = new javax.swing.JPanel();
        jlabel_editar_salida = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlabel_nueva_salida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabel_nlista_salidas = new javax.swing.JLabel();
        btn_searxhSalida = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jday_salida = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_ENTRADAPRODUCTOS = new javax.swing.JTable();

        setBackground(new java.awt.Color(43, 43, 43));
        setForeground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(890, 660));
        setMinimumSize(new java.awt.Dimension(890, 660));
        setPreferredSize(new java.awt.Dimension(890, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(43, 43, 43));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jpanel_fondo.setBackground(new java.awt.Color(255, 255, 255));
        Jpanel_fondo.setForeground(new java.awt.Color(153, 153, 153));

        jlabel_editar_salida.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_editar_salida.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_editar_salida.setForeground(new java.awt.Color(51, 51, 51));
        jlabel_editar_salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit_prod.png"))); // NOI18N
        jlabel_editar_salida.setText("EDITAR SALIDA ");
        jlabel_editar_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_editar_salidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_editar_salidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_editar_salidaMouseExited(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));

        jlabel_nueva_salida.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_nueva_salida.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_nueva_salida.setForeground(new java.awt.Color(51, 51, 51));
        jlabel_nueva_salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new_entrad.png"))); // NOI18N
        jlabel_nueva_salida.setText("NUEVA SALIDA");
        jlabel_nueva_salida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_nueva_salidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_nueva_salidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_nueva_salidaMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BUSCAR SALIDA DE PRODUCTOS");

        jlabel_nlista_salidas.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_nlista_salidas.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_nlista_salidas.setForeground(new java.awt.Color(51, 51, 51));
        jlabel_nlista_salidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/list.png"))); // NOI18N
        jlabel_nlista_salidas.setText("LISTA DE SALIDAS");
        jlabel_nlista_salidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_nlista_salidasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_nlista_salidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_nlista_salidasMouseExited(evt);
            }
        });

        btn_searxhSalida.setBackground(new java.awt.Color(36, 36, 36));
        btn_searxhSalida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 36, 36), 4, true));
        btn_searxhSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searxhSalidaMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buscar_inventario.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btn_searxhSalidaLayout = new javax.swing.GroupLayout(btn_searxhSalida);
        btn_searxhSalida.setLayout(btn_searxhSalidaLayout);
        btn_searxhSalidaLayout.setHorizontalGroup(
            btn_searxhSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_searxhSalidaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );
        btn_searxhSalidaLayout.setVerticalGroup(
            btn_searxhSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_searxhSalidaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TABLA_ENTRADAPRODUCTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Tipo", "Encargado", "Almacen", "Cantidad", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(TABLA_ENTRADAPRODUCTOS);

        javax.swing.GroupLayout Jpanel_fondoLayout = new javax.swing.GroupLayout(Jpanel_fondo);
        Jpanel_fondo.setLayout(Jpanel_fondoLayout);
        Jpanel_fondoLayout.setHorizontalGroup(
            Jpanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_fondoLayout.createSequentialGroup()
                .addGroup(Jpanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Jpanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Jpanel_fondoLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_fondoLayout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(jlabel_nlista_salidas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(100, 100, 100)
                            .addComponent(jlabel_nueva_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112)
                            .addComponent(jlabel_editar_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_fondoLayout.createSequentialGroup()
                            .addGap(321, 321, 321)
                            .addComponent(jday_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_searxhSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_fondoLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Jpanel_fondoLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        Jpanel_fondoLayout.setVerticalGroup(
            Jpanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jpanel_fondoLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(Jpanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel_nlista_salidas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_nueva_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel_editar_salida))
                .addGap(22, 22, 22)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Jpanel_fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jday_salida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_searxhSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        fondo.add(Jpanel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 670));

        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel_nlista_salidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nlista_salidasMouseExited
        jlabel_nlista_salidas.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_nlista_salidasMouseExited

    private void jlabel_nlista_salidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nlista_salidasMouseEntered
        jlabel_nlista_salidas.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_nlista_salidasMouseEntered

    private void jlabel_nueva_salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_salidaMouseExited
        jlabel_nueva_salida.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_nueva_salidaMouseExited

    private void jlabel_nueva_salidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_salidaMouseEntered
        jlabel_nueva_salida.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_nueva_salidaMouseEntered

    private void jlabel_editar_salidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_salidaMouseExited
        jlabel_editar_salida.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_editar_salidaMouseExited

    private void jlabel_editar_salidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_salidaMouseEntered
        jlabel_editar_salida.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_editar_salidaMouseEntered

    private void jlabel_nlista_salidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nlista_salidasMouseClicked
          Salida_vista nueva= new Salida_vista();
          addConatiner(nueva, width, height, Jpanel_fondo);
    }//GEN-LAST:event_jlabel_nlista_salidasMouseClicked

    private void jlabel_nueva_salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nueva_salidaMouseClicked
          Salida_Nueva nueva= new Salida_Nueva();
          addConatiner(nueva, width, height, Jpanel_fondo);
    }//GEN-LAST:event_jlabel_nueva_salidaMouseClicked

    private void jlabel_editar_salidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_editar_salidaMouseClicked
          Salida_vista nueva= new Salida_vista();
          addConatiner(nueva, width, height, Jpanel_fondo);
          JOptionPane.showMessageDialog(null, "Selecciona un elemento de la tabla a editar", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jlabel_editar_salidaMouseClicked

    private void btn_searxhSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searxhSalidaMouseClicked
       if(jday_salida.getDate() != null){
            DefaultTableModel modelo_entrada = new DefaultTableModel();
            modelo_entrada= metodos_salida.search_Fecha(conversion(jday_salida.getDate()));
            if(modelo_entrada.getRowCount()>0){
                TABLA_ENTRADAPRODUCTOS.setModel(modelo_entrada);
            }else{
                JOptionPane.showMessageDialog(null, "No se encontro ninguna entrada durante la fecha: "+conversion(jday_salida.getDate()) ,"",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese una fecha!" ,"",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_searxhSalidaMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    
    
    
    public void Look() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {

        } catch (IllegalAccessException ex) {

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel_fondo;
    private javax.swing.JTable TABLA_ENTRADAPRODUCTOS;
    private javax.swing.JPanel btn_searxhSalida;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JDateChooser jday_salida;
    private javax.swing.JLabel jlabel_editar_salida;
    private javax.swing.JLabel jlabel_nlista_salidas;
    private javax.swing.JLabel jlabel_nueva_salida;
    // End of variables declaration//GEN-END:variables
    public void addConatiner(JPanel p,int width, int height,JPanel c){
        p.setSize(width,height);
        p.setLocation(0,0);
        c.removeAll();
        c.add(p,BorderLayout.CENTER);
        c.revalidate();
        c.repaint();
    }
    
    
    String conversion(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = sdf.format(date);
        System.out.println("FECHA:" + fecha);
        return fecha;
    }
    
}
