/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sub_jpanel;

import SqlMetodos.Trabajadores_sql;
import jpanel.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Julio Ramirez
 */
public class Trabajadores_buscar extends javax.swing.JPanel {
     int width=890, height=630;
    /**
     * Creates new form Inicio
     */
     
    Trabajadores_sql metodos_trbj = new Trabajadores_sql();
    public Trabajadores_buscar() {
        initComponents();
        listar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        list_jpnael = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JPanel();
        jlabel_buscar_producto = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_TRBJ_FOTO = new javax.swing.JTable();
        jday_buscarTrbj = new com.toedter.calendar.JDateChooser();
        jSeparator3 = new javax.swing.JSeparator();
        jlabel_lista_trbj = new javax.swing.JLabel();
        jlabel_nuevo_trbj = new javax.swing.JLabel();
        jlabel_lista_editar_trbj = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(890, 660));
        setMinimumSize(new java.awt.Dimension(890, 660));
        setPreferredSize(new java.awt.Dimension(890, 660));

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list_jpnael.setBackground(new java.awt.Color(43, 43, 43));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BUSCAR TRABAJADOR");

        btn_buscar.setBackground(new java.awt.Color(30, 30, 30));
        btn_buscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });

        jlabel_buscar_producto.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_producto.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_buscar_producto.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buscar_inventario.png"))); // NOI18N
        jlabel_buscar_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_buscar_productoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_buscar_productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_buscar_productoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_buscarLayout = new javax.swing.GroupLayout(btn_buscar);
        btn_buscar.setLayout(btn_buscarLayout);
        btn_buscarLayout.setHorizontalGroup(
            btn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_buscarLayout.createSequentialGroup()
                .addComponent(jlabel_buscar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btn_buscarLayout.setVerticalGroup(
            btn_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_buscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlabel_buscar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TABLA_TRBJ_FOTO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombres", "Apellidos", "Cargo", "Fecha_ingreso", "Foto"
            }
        ));
        jScrollPane1.setViewportView(TABLA_TRBJ_FOTO);
        if (TABLA_TRBJ_FOTO.getColumnModel().getColumnCount() > 0) {
            TABLA_TRBJ_FOTO.getColumnModel().getColumn(0).setMinWidth(30);
            TABLA_TRBJ_FOTO.getColumnModel().getColumn(0).setPreferredWidth(30);
            TABLA_TRBJ_FOTO.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));

        jlabel_lista_trbj.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_lista_trbj.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_lista_trbj.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_lista_trbj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lista.png"))); // NOI18N
        jlabel_lista_trbj.setText("LISTA DE TRABAJADORES");
        jlabel_lista_trbj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_lista_trbjMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_lista_trbjMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_lista_trbjMouseExited(evt);
            }
        });

        jlabel_nuevo_trbj.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_nuevo_trbj.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_nuevo_trbj.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_nuevo_trbj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Trabajadores.png"))); // NOI18N
        jlabel_nuevo_trbj.setText("NUEVO TRABAJADOR");
        jlabel_nuevo_trbj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_nuevo_trbjMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_nuevo_trbjMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_nuevo_trbjMouseExited(evt);
            }
        });

        jlabel_lista_editar_trbj.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_lista_editar_trbj.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_lista_editar_trbj.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_lista_editar_trbj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Editar_producto.png"))); // NOI18N
        jlabel_lista_editar_trbj.setText("EDITAR TRABAJADOR");
        jlabel_lista_editar_trbj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_lista_editar_trbjMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_lista_editar_trbjMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_lista_editar_trbjMouseExited(evt);
            }
        });

        javax.swing.GroupLayout list_jpnaelLayout = new javax.swing.GroupLayout(list_jpnael);
        list_jpnael.setLayout(list_jpnaelLayout);
        list_jpnaelLayout.setHorizontalGroup(
            list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_jpnaelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jlabel_lista_trbj)
                .addGap(123, 123, 123)
                .addComponent(jlabel_nuevo_trbj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabel_lista_editar_trbj)
                .addGap(64, 64, 64))
            .addGroup(list_jpnaelLayout.createSequentialGroup()
                .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(list_jpnaelLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jday_buscarTrbj, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(list_jpnaelLayout.createSequentialGroup()
                        .addGap(700, 700, 700)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(list_jpnaelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(list_jpnaelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        list_jpnaelLayout.setVerticalGroup(
            list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_jpnaelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_lista_trbj)
                    .addComponent(jlabel_nuevo_trbj)
                    .addComponent(jlabel_lista_editar_trbj))
                .addGap(36, 36, 36)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jday_buscarTrbj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
        );

        fondo.add(list_jpnael, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel_buscar_productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_productoMouseEntered
        jlabel_buscar_producto.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_buscar_productoMouseEntered

    private void jlabel_buscar_productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_productoMouseExited
        jlabel_buscar_producto.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_buscar_productoMouseExited

    private void jlabel_lista_trbjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_trbjMouseClicked
        Lista_Trbj nueva= new Lista_Trbj();
        addConatiner(nueva, width, height, list_jpnael);
    }//GEN-LAST:event_jlabel_lista_trbjMouseClicked

    private void jlabel_lista_trbjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_trbjMouseEntered
        jlabel_lista_trbj.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_lista_trbjMouseEntered

    private void jlabel_lista_trbjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_trbjMouseExited
        jlabel_lista_trbj.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_lista_trbjMouseExited

    private void jlabel_nuevo_trbjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nuevo_trbjMouseClicked
        Trabajadores_ingresooo nueva= new Trabajadores_ingresooo();
        addConatiner(nueva, width, height, list_jpnael);
    }//GEN-LAST:event_jlabel_nuevo_trbjMouseClicked

    private void jlabel_nuevo_trbjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nuevo_trbjMouseEntered
        jlabel_nuevo_trbj.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_nuevo_trbjMouseEntered

    private void jlabel_nuevo_trbjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_nuevo_trbjMouseExited
        jlabel_nuevo_trbj.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_nuevo_trbjMouseExited

    private void jlabel_lista_editar_trbjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_editar_trbjMouseClicked
        Lista_Trbj nueva= new Lista_Trbj();
        addConatiner(nueva, width, height, list_jpnael);
        JOptionPane.showMessageDialog(null, "Seleccione un elemento de la tabla que deseas editar", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jlabel_lista_editar_trbjMouseClicked

    
    private void jlabel_lista_editar_trbjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_editar_trbjMouseEntered
        jlabel_lista_editar_trbj.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_lista_editar_trbjMouseEntered

    private void jlabel_lista_editar_trbjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_editar_trbjMouseExited
        jlabel_lista_editar_trbj.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_lista_editar_trbjMouseExited

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        if(jday_buscarTrbj.getDate() != null){
            String f_search = conversion(jday_buscarTrbj.getDate());
            metodos_trbj.llenar_Busqueda(TABLA_TRBJ_FOTO);
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese una fecha para encontrar a los trabajadores", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void jlabel_buscar_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_productoMouseClicked
        if(jday_buscarTrbj.getDate() != null){
            String f_search = conversion(jday_buscarTrbj.getDate());
            metodos_trbj.search_Trbj(f_search);
            metodos_trbj.llenar_Busqueda(TABLA_TRBJ_FOTO);
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese una fecha para encontrar a los trabajadores", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jlabel_buscar_productoMouseClicked

    
     public void addConatiner(JPanel p,int width, int height,JPanel c){
        p.setSize(width,height);
        p.setLocation(0,0);
        c.removeAll();
        c.add(p,BorderLayout.CENTER);
        c.revalidate();
        c.repaint();
    }
    
    public void Look() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {

        } catch (IllegalAccessException ex) {

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLA_TRBJ_FOTO;
    private javax.swing.JPanel btn_buscar;
    private java.awt.Canvas canvas1;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JDateChooser jday_buscarTrbj;
    private javax.swing.JLabel jlabel_buscar_producto;
    private javax.swing.JLabel jlabel_lista_editar_trbj;
    private javax.swing.JLabel jlabel_lista_trbj;
    private javax.swing.JLabel jlabel_nuevo_trbj;
    private javax.swing.JPanel list_jpnael;
    // End of variables declaration//GEN-END:variables

    
    public void listar(){
        metodos_trbj.llenar_tabla(TABLA_TRBJ_FOTO);
    }
    
    String conversion(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = sdf.format(date);
        System.out.println("FECHA:" + fecha);
        return fecha;
    }
    
}
