/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sub_jpanel;

import BOL.Trabajador;
import SqlMetodos.Trabajadores_sql;
import jpanel.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Julio Ramirez
 */
public class Trabajadores_propiedad extends javax.swing.JPanel {
    int width=890, height=630;
    private ImageIcon image;
    private Icon icono;
    String ruta = null;
    JFileChooser seleccion_img = new JFileChooser();
    File archivo_img;
    
    Trabajadores_sql metodos_trbj = new Trabajadores_sql();
    String codigo_capturado; 
    
    public Trabajadores_propiedad() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        list_jpnael = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jSeparator3 = new javax.swing.JSeparator();
        jlabel_lista_trbj = new javax.swing.JLabel();
        jlabel_lista_editar_trbj = new javax.swing.JLabel();
        jlabel_buscar_trbj = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        jpanel_foto = new javax.swing.JPanel();
        jlabel_foto = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcombo_cargo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jday_fecha_nac = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jday_fecha_ingreso = new com.toedter.calendar.JDateChooser();
        jlabel_edit_trbj = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jlabel_delete_trbj = new javax.swing.JLabel();
        btn_subirFoto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(890, 660));
        setMinimumSize(new java.awt.Dimension(890, 660));
        setPreferredSize(new java.awt.Dimension(890, 660));

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list_jpnael.setBackground(new java.awt.Color(43, 43, 43));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" PROPIEDAD DEL TRABAJADOR");

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));

        jlabel_lista_trbj.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_lista_trbj.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_lista_trbj.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_lista_trbj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lista.png"))); // NOI18N
        jlabel_lista_trbj.setText("LISTA DE TRABAJADORES");
        jlabel_lista_trbj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_lista_trbjMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_lista_trbjMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_lista_trbjMouseExited(evt);
            }
        });

        jlabel_lista_editar_trbj.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_lista_editar_trbj.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_lista_editar_trbj.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_lista_editar_trbj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Editar_producto.png"))); // NOI18N
        jlabel_lista_editar_trbj.setText("EDITAR TRABAJADOR");
        jlabel_lista_editar_trbj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_lista_editar_trbjMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_lista_editar_trbjMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_lista_editar_trbjMouseExited(evt);
            }
        });

        jlabel_buscar_trbj.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_trbj.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_buscar_trbj.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_buscar_trbj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/buscar_trabajor.png"))); // NOI18N
        jlabel_buscar_trbj.setText("BUSCAR TRABAJADOR");
        jlabel_buscar_trbj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_buscar_trbjMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_buscar_trbjMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_buscar_trbjMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new_Entrada.png"))); // NOI18N
        jLabel9.setText("DATOS PERSONALES");

        jLabel19.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("NOMBRES");

        txt_nombre.setBackground(new java.awt.Color(43, 43, 43));
        txt_nombre.setForeground(new java.awt.Color(153, 153, 153));
        txt_nombre.setBorder(null);

        jLabel16.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("APELLIDOS");

        txt_apellidos.setBackground(new java.awt.Color(43, 43, 43));
        txt_apellidos.setForeground(new java.awt.Color(153, 153, 153));
        txt_apellidos.setBorder(null);

        jpanel_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpanel_fotoLayout = new javax.swing.GroupLayout(jpanel_foto);
        jpanel_foto.setLayout(jpanel_fotoLayout);
        jpanel_fotoLayout.setHorizontalGroup(
            jpanel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabel_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jpanel_fotoLayout.setVerticalGroup(
            jpanel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlabel_foto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("CARGO");

        jcombo_cargo.setBackground(new java.awt.Color(43, 43, 43));
        jcombo_cargo.setForeground(new java.awt.Color(153, 153, 153));
        jcombo_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Soldador", "Electricista", "Mecanico", "Ayudante" }));

        jLabel17.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fehca_registro.png"))); // NOI18N
        jLabel17.setText("FECHAS REGISTRADAS");

        jLabel20.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("FECHA DE NACIMIENTO");

        jday_fecha_nac.setBackground(new java.awt.Color(43, 43, 43));

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("FECHA DE INGRESO");

        jday_fecha_ingreso.setBackground(new java.awt.Color(43, 43, 43));

        jlabel_edit_trbj.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_edit_trbj.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_edit_trbj.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_edit_trbj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        jlabel_edit_trbj.setText("EDITAR TRABAJADOR");
        jlabel_edit_trbj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_edit_trbjMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_edit_trbjMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_edit_trbjMouseExited(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));

        jlabel_delete_trbj.setBackground(new java.awt.Color(153, 153, 153));
        jlabel_delete_trbj.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jlabel_delete_trbj.setForeground(new java.awt.Color(153, 153, 153));
        jlabel_delete_trbj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete_trbj.png"))); // NOI18N
        jlabel_delete_trbj.setText("ELIMINAR TRABAJADOR");
        jlabel_delete_trbj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_delete_trbjMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlabel_delete_trbjMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlabel_delete_trbjMouseExited(evt);
            }
        });

        btn_subirFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_subirFotoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jLabel1.setText("                SUBIR FOTO");

        javax.swing.GroupLayout btn_subirFotoLayout = new javax.swing.GroupLayout(btn_subirFoto);
        btn_subirFoto.setLayout(btn_subirFotoLayout);
        btn_subirFotoLayout.setHorizontalGroup(
            btn_subirFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );
        btn_subirFotoLayout.setVerticalGroup(
            btn_subirFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout list_jpnaelLayout = new javax.swing.GroupLayout(list_jpnael);
        list_jpnael.setLayout(list_jpnaelLayout);
        list_jpnaelLayout.setHorizontalGroup(
            list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_jpnaelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, list_jpnaelLayout.createSequentialGroup()
                            .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(list_jpnaelLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel9))
                                .addGroup(list_jpnaelLayout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jcombo_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(list_jpnaelLayout.createSequentialGroup()
                                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(60, 60, 60)
                                            .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(list_jpnaelLayout.createSequentialGroup()
                                                    .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(132, 132, 132)
                                                    .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(list_jpnaelLayout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addGap(174, 174, 174)
                                            .addComponent(jLabel16))
                                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jpanel_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(list_jpnaelLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jday_fecha_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(372, 372, 372)
                            .addComponent(btn_subirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(list_jpnaelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel17)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(list_jpnaelLayout.createSequentialGroup()
                .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(list_jpnaelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(list_jpnaelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jlabel_lista_trbj)
                        .addGap(95, 95, 95)
                        .addComponent(jlabel_buscar_trbj)
                        .addGap(132, 132, 132)
                        .addComponent(jlabel_lista_editar_trbj))
                    .addGroup(list_jpnaelLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jday_fecha_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(list_jpnaelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabel_edit_trbj)
                .addGap(184, 184, 184)
                .addComponent(jlabel_delete_trbj)
                .addGap(178, 178, 178))
        );
        list_jpnaelLayout.setVerticalGroup(
            list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_jpnaelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel_lista_trbj)
                    .addComponent(jlabel_buscar_trbj)
                    .addComponent(jlabel_lista_editar_trbj))
                .addGap(48, 48, 48)
                .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(list_jpnaelLayout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpanel_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(list_jpnaelLayout.createSequentialGroup()
                        .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(list_jpnaelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel16)
                                .addGap(0, 0, 0)
                                .addComponent(txt_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(list_jpnaelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(list_jpnaelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcombo_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(list_jpnaelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(list_jpnaelLayout.createSequentialGroup()
                        .addComponent(btn_subirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(list_jpnaelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(list_jpnaelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jday_fecha_nac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(list_jpnaelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jday_fecha_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36)
                .addGroup(list_jpnaelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_edit_trbj)
                    .addComponent(jlabel_delete_trbj))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        fondo.add(list_jpnael, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlabel_lista_editar_trbjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_editar_trbjMouseExited
        jlabel_lista_editar_trbj.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_lista_editar_trbjMouseExited

    private void jlabel_lista_editar_trbjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_editar_trbjMouseEntered
        jlabel_lista_editar_trbj.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_lista_editar_trbjMouseEntered

    private void jlabel_lista_editar_trbjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_editar_trbjMouseClicked
        Lista_Trbj nueva= new Lista_Trbj();
        addConatiner(nueva, width, height, list_jpnael);
        JOptionPane.showMessageDialog(null, "Seleccione un elemento de la tabla que deseas editar", "", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jlabel_lista_editar_trbjMouseClicked

    private void jlabel_lista_trbjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_trbjMouseExited
        jlabel_lista_trbj.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_lista_trbjMouseExited

    private void jlabel_lista_trbjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_trbjMouseEntered
        jlabel_lista_trbj.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_lista_trbjMouseEntered

    private void jlabel_lista_trbjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_lista_trbjMouseClicked
        Lista_Trbj nueva= new Lista_Trbj();
        addConatiner(nueva, width, height, list_jpnael);
    }//GEN-LAST:event_jlabel_lista_trbjMouseClicked

    private void jlabel_buscar_trbjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_trbjMouseClicked
        Trabajadores_buscar nueva= new Trabajadores_buscar();
        addConatiner(nueva, width, height, list_jpnael);
    }//GEN-LAST:event_jlabel_buscar_trbjMouseClicked

    private void jlabel_buscar_trbjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_trbjMouseEntered
        jlabel_buscar_trbj.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_buscar_trbjMouseEntered

    private void jlabel_buscar_trbjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_buscar_trbjMouseExited
        jlabel_buscar_trbj.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_buscar_trbjMouseExited

    private void jlabel_edit_trbjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_edit_trbjMouseClicked
        if(!txt_apellidos.getText().equals("") & !txt_nombre.getText().equals("") & jday_fecha_ingreso.getDate() != null & jday_fecha_nac != null){        
            Trabajador t = new Trabajador();
            t.setId(id_trbjador(txt_apellidos.getText()));
            t.setNombres(txt_nombre.getText());
            t.setApellidos(txt_apellidos.getText());
            t.setCargo(jcombo_cargo.getSelectedItem().toString());
            t.setNacimiento(conversion(jday_fecha_nac.getDate()));
            t.setFecha_ingreso(conversion(jday_fecha_ingreso.getDate()));
            metodos_trbj.update_Trbj(t,codigo_capturado,archivo_img.toString());
            metodos_trbj.listar_Trbj();//Actualizacion de datos
            vaciar();
        }else{  
            JOptionPane.showMessageDialog(null, "Termine de llenar los campos de ingreso", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jlabel_edit_trbjMouseClicked

    private void jlabel_edit_trbjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_edit_trbjMouseEntered
        jlabel_edit_trbj.setForeground(new Color(45,130,215));
    }//GEN-LAST:event_jlabel_edit_trbjMouseEntered

    private void jlabel_edit_trbjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_edit_trbjMouseExited
        jlabel_edit_trbj.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_edit_trbjMouseExited

    private void jlabel_delete_trbjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_delete_trbjMouseClicked
        String[] opciones={"Si","No"};
        int menu = JOptionPane.showOptionDialog(null, "¿Desea eliminar los datos del trabajador?", "",JOptionPane.WARNING_MESSAGE,JOptionPane.WARNING_MESSAGE, null, opciones, "Si");
        switch(menu){
            case 0:
                metodos_trbj.delete_Trbj(codigo_capturado);
                vaciar();
                metodos_trbj.listar_Trbj();
                Lista_Trbj trbj_vista = new Lista_Trbj();
                addConatiner(trbj_vista, width, height, list_jpnael);
                break;
        }
    }//GEN-LAST:event_jlabel_delete_trbjMouseClicked

    private void jlabel_delete_trbjMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_delete_trbjMouseEntered
        jlabel_delete_trbj.setForeground(Color.red);
    }//GEN-LAST:event_jlabel_delete_trbjMouseEntered

    private void jlabel_delete_trbjMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_delete_trbjMouseExited
        jlabel_delete_trbj.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_jlabel_delete_trbjMouseExited

    private void btn_subirFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subirFotoMouseClicked
        if(seleccion_img.showDialog(null, "Seleccionar Foto") == JFileChooser.APPROVE_OPTION){
                 archivo_img = seleccion_img.getSelectedFile(); //Guardamos la ruita sleeccionada para guardarla y mostrarla en la tabla                 
                 if(archivo_img.getName().endsWith("jpg") || archivo_img.getName().endsWith("png")|| archivo_img.getName().endsWith("PNG") ||archivo_img.getName().endsWith("svg") ){
                     ajustarImagen(jlabel_foto, archivo_img.toString());
                     //Metodo par guardar la iamgen en la base de datos;
                 }else{
                     JOptionPane.showMessageDialog(null, "El formato deve ser de tipo imagen","Error",JOptionPane.ERROR_MESSAGE);
                 }
        }
    }//GEN-LAST:event_btn_subirFotoMouseClicked

    
    
     public void addConatiner(JPanel p,int width, int height,JPanel c){
        p.setSize(width,height);
        p.setLocation(0,0);
        c.removeAll();
        c.add(p,BorderLayout.CENTER);
        c.revalidate();
        c.repaint();
    }
    
    public void Look() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {

        } catch (IllegalAccessException ex) {

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_subirFoto;
    private java.awt.Canvas canvas1;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> jcombo_cargo;
    private com.toedter.calendar.JDateChooser jday_fecha_ingreso;
    private com.toedter.calendar.JDateChooser jday_fecha_nac;
    private javax.swing.JLabel jlabel_buscar_trbj;
    private javax.swing.JLabel jlabel_delete_trbj;
    private javax.swing.JLabel jlabel_edit_trbj;
    private javax.swing.JLabel jlabel_foto;
    private javax.swing.JLabel jlabel_lista_editar_trbj;
    private javax.swing.JLabel jlabel_lista_trbj;
    private javax.swing.JPanel jpanel_foto;
    private javax.swing.JPanel list_jpnael;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

    
    /**********************************METODOS DE INGRESO***************************************/
    
    /*CONVERSION DE LAS FECHAS*/
    String conversion(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = sdf.format(date);
        System.out.println("FECHA:" + fecha);
        return fecha;
    }
    
    String id_trbjador(String apellido){
        String result="";
        int cantidad = (int)(Math.random()*10+1);
            result= "tj"+apellido.substring(0,2)+cantidad;
        return result;
    }
    
    /*METODOS INTERFAZ*/
    void vaciar(){
        txt_apellidos.setText("");
        txt_nombre.setText("");
        jcombo_cargo.setSelectedItem(0);
        jday_fecha_ingreso.setDate(null);
        jday_fecha_nac.setDate(null);
    }
    
    /*Escalado de iamgen para la foto del trabajador*/
     private void ajustarImagen(JLabel l, String path){
        this.image = new ImageIcon(path);
        this.icono = new ImageIcon(image.getImage().getScaledInstance(l.getWidth(), l.getHeight(), Image.SCALE_DEFAULT));
        l.setIcon(icono);
        this.repaint();
    }
    
    private void ajustarIcon(JLabel l, ImageIcon lj){
        System.out.println("LLEGUE  AJAUSTAR");
        this.image = lj;
        this.icono = new ImageIcon(image.getImage().getScaledInstance(l.getWidth(), l.getHeight(), Image.SCALE_DEFAULT));
        l.setIcon(icono);
        this.repaint();
    }
    
    /*****************************METODOS ACTUALISAR****************************************/
    /*Traspaso de datos de la fila 
        *seleccionada en la 
        *lista trabajadores
    */
    
    public void rellenado (Trabajador t, Date f_ingreso, Date f_nac){
        codigo_capturado = t.getId();
        txt_nombre.setText(t.getNombres());
        txt_apellidos.setText(t.getApellidos());
        jcombo_cargo.setSelectedItem(t.getCargo());
        jday_fecha_ingreso.setDate(f_ingreso);
        jday_fecha_nac.setDate(f_nac);
        System.out.println("CODIGO CAPTURADO:"+ codigo_capturado);
        ImageIcon img = metodos_trbj.search_img(codigo_capturado);
        jlabel_foto.setIcon(img); 
        //ajustarIcon(jlabel_foto, img);
    }
    
    

}
